Add docs on serving with Llama Stack
vllm-project/vllm pull request #10183
Opened 2024-11-09 13:04 UTC by terrytangyuan

See guide in https://github.com/meta-llama/llama-stack/blob/main/docs/source/getting_started/distributions/self_hosted_distro/remote_vllm.md

2024-11-09 14:18 UTC, russellb requested changes
want to mention the inline integration, as well?

https://github.com/meta-llama/llama-stack/tree/main/llama_stack/providers/inline/inference/vllm

2024-11-09 15:52 UTC, terrytangyuan commented
Definitely! I'll update this in a bit. Let me see if I can find the relevant guide. I wasn't sure if that's available yet.

2024-11-09 16:09 UTC, terrytangyuan commented
@russellb I couldn't find a guide yet but I have added a reference to the inline implementation.

2024-11-10 15:34 UTC, russellb requested changes
Suggested an addition of sample config

2024-11-10 15:34 UTC, russellb commented on docs/source/serving/serving_with_llamastack.rst
> +Please refer to `this guide <https://github.com/meta-llama/llama-stack/blob/main/docs/source/getting_started/distributions/self_hosted_distro/remote_vllm.md>`_ for more details on this remote vLLM pr
```suggestion
Inference using OpenAI Compatible API
-------------------------------------

Then start Llama Stack server pointing to your vLLM server with the following configuration:

.. code-block:: yaml

    inference:
      - provider_id: vllm0
        provider_type: remote::vllm
        config:
          url: http://127.0.0.1:8000

Please refer to `this guide <https://github.com/meta-llama/llama-stack/blob/main/docs/source/getting_started/distributions/self_hosted_distro/remote_vllm.md>`_ for more details on this remote vLLM provider.

Inference via Embedded vLLM
---------------------------

An `inline vLLM provider
<https://github.com/meta-llama/llama-stack/tree/main/llama_stack/providers/inline/inference/vllm>`_
is also available. This is a sample of configuration using that method:

.. code-block:: yaml

    inference
      - provider_type: vllm
        config:
          model: Llama3.1-8B-Instruct
          tensor_parallel_size: 4
```

2024-11-11 02:26 UTC, terrytangyuan commented
Thanks! Looking good.

2024-11-11 15:38 UTC, russellb approved these changes
Other than adding `Signed-off-by` to the commits so DCO will pass, this lgtm now. Thanks!

Feel free to add my `Signed-off-by` to the co-authored commit with my addition.

2024-11-11 15:50 UTC, russellb requested changes
Actually, I think you need one more change. Right now you'll get an error that this page is not listed anywhere:

```
checking consistency... /Users/rbryant/src/vllm/docs/source/serving/serving_with_llamastack.rst: WARNING: document isn't included in any toctree
```

I would add this to  `docs/source/serving/integrations.rst`

2024-11-11 16:37 UTC, terrytangyuan commented
Should be fixed now!

2024-11-11 18:00 UTC, terrytangyuan commented
Build failures seem unrelated.

2024-11-11 19:19 UTC, russellb approved these changes
thanks!

2024-11-11 19:28 UTC, youkaichao approved these changes
thanks for the integration!

2024-11-11 19:28 UTC, merged