Remove AsyncLLMEngine busy loop, shield bg task
vllm-project/vllm pull request #1059
Opened 2023-09-15 22:03 UTC by Yard1

This PR reduces CPU utilisation of `AsyncLLMEngine` by replacing busy looping with an `asyncio.Event` triggered whenever there are new requests, and makes sure that the background loop task is shielded from cancellation.

2023-09-15 22:03 UTC, Yard1 commented
cc @zhuohan123

2023-09-16 00:32 UTC, zhuohan123 requested changes

2023-09-16 00:32 UTC, zhuohan123 commented on vllm/engine/async_llm_engine.py
> +from typing import Any, Callable, Coroutine, Dict, Iterable, List, Optional, Set, Tuple, Type, Union
Nit: add parenthesis around this long import and then run the formatter.
```suggestion
from typing import (Any, Callable, Coroutine, Dict, Iterable, List, Optional, Set, Tuple, Type, Union)
```

2023-09-16 00:32 UTC, zhuohan123 commented on vllm/engine/async_llm_engine.py
> +
Nit: redundant new line
```suggestion
```

2023-09-16 00:32 UTC, zhuohan123 commented on vllm/engine/async_llm_engine.py
> +        self.background_loop = self._task_set.run(
if this `task_set` will only have one task, why is a "set" needed? Can we just shield the background loop?

2023-09-16 00:32 UTC, zhuohan123 commented on vllm/engine/async_llm_engine.py
> +        return bool(request_outputs)
Nit: Make the code a bit easier to understand:
```suggestion
        return len(request_outputs) > 0
```

2023-09-16 00:39 UTC, Yard1 commented on vllm/engine/async_llm_engine.py
> +
added by formattter

2023-09-17 07:29 UTC, zhuohan123 approved these changes
LGTM! Thanks for the fix!

2023-09-17 07:29 UTC, merged