[V1][WIP] V1 sampler implements parallel sampling (PR 1/N for parallel sampling support)
vllm-project/vllm pull request #10980
Opened 2024-12-07 17:49 UTC by afeldman-nm

The vLLM V1 sampler will support parallel sampling. 

Currently the sampler consumes a logits vector which is concatenated over all requests, i.e. the logits vector is `total_batch_tokens x vocab_size`. Each request contributes a single completion.

Now the sampler will consume a logits vector which is `total_tokens x vocab_size` where `total_tokens` is the sum of the sequence lengths of all ongoing completions for all requests, allowing that a request may have more than one completion.

TODO: understand how to exploit prefix caching for parallel sampling?

PR 1/N towards addressing the known need for vLLM v1 parallel sampling support (as described in the vLLM's V1 Engine Architecture RFC)

**BEFORE SUBMITTING, PLEASE READ https://docs.vllm.ai/en/latest/contributing/overview.html **

2025-01-30 23:57 UTC, FrederickVu commented
It seems like this PR is implementing ideas similar to those implemented in PR #9302 for the V0 engine. That PR created some issues that were addressed in PR #11898 and which may exist in the proposed V1 code. 

In particular, the proposed code currently does not properly handle the case when a seed value is provided for the parent request; the seed value is duplicated in child requests, leading to identical outputs in the child requests. The fix in #11898 was simply to move the copying of the `SamplingParams` object inside a for-loop and to increment the seed value of the parent request. 

Additionally, the proposed code for the V1 engine defines `get_num_unfinished_requests()` in a way that is currently incompatible with the same function for the V0 engine (though it's really the V0 engine's code which is in the wrong, I am choosing to mention this here as it seems relevant and the PR is still open). In the V0 engine, that function actually counts the number of `SequenceGroup` objects in the engine as opposed to the number of requests. This led to bugs mentioned in Issues #10949 and #11519, and an attempt to fix them is in PR #12428. However, the proposed fix is not compatible with the proposed V1 code. I will comment on that PR as well so that maintainers can adapt the V0 code to align with the proposed V1 code.

2025-02-11 15:28 UTC, afeldman-nm commented
> It seems like this PR is implementing ideas similar to those implemented in PR #9302 for the V0 engine. That PR created some issues that were addressed in PR #11898 and which may exist in the proposed V1 code.
> 
> In particular, the proposed code currently does not properly handle the case when a seed value is provided for the parent request; the seed value is duplicated in child requests, leading to identical outputs in the child requests. The fix in #11898 was simply to move the copying of the `SamplingParams` object inside a for-loop and to increment the seed value of the parent request.
> 
> Additionally, the proposed code for the V1 engine defines `get_num_unfinished_requests()` in a way that is currently incompatible with the same function for the V0 engine (though it's really the V0 engine's code which is in the wrong, I am choosing to mention this here as it seems relevant and the PR is still open). In the V0 engine, that function actually counts the number of `SequenceGroup` objects in the engine as opposed to the number of requests. This led to bugs mentioned in Issues #10949 and #11519, and an attempt to fix them is in PR #12428. However, the proposed fix is not compatible with the proposed V1 code. I will comment on that PR as well so that maintainers can adapt the V0 code to align with the proposed V1 code.

Hi @FrederickVu , thank you for this feedback. I re-implemented this PR from scratch & ensured that if a non-`None` `seed` value is provided to `sampling_params`, then each child request has a different integer seed value (basically what you described - increment `seed` in a loop.)

As for `get_num_unfinished_requests`, the new implementation of this PR does not rely on this function.

2025-02-11 18:24 UTC, robertgshaw2-redhat commented on vllm/v1/engine/async_llm.py
> +            async for out in self._parallel_sampling_batch(
Its a bit confusing to call this `_parallel_sampling_batch`, since it is not a batch. How about `_generate_parallel_sampling`

2025-02-11 18:24 UTC, robertgshaw2-redhat commented on vllm/v1/engine/async_llm.py
> +            w_sampling_params = parent_state.get_child_sampling_params({
to keep the code simple and the logic isolated, can we just have a function called `parent_state.warmup_sampling_params()`?

2025-02-11 18:24 UTC, robertgshaw2-redhat commented on vllm/v1/engine/async_llm.py
> +            c_sampling_params = parent_state.get_child_sampling_params({
we should only need to pass `seed` here right?

2025-02-11 18:25 UTC, robertgshaw2-redhat commented on vllm/v1/engine/async_llm.py
> +    async def _parallel_sampling_batch(
should add `adapted from sglang: link to sglang code`

2025-02-13 00:50 UTC, njhill reviewed
Thanks @afeldman-nm, I have quite a few comments, mostly simplification.

I guess in the non-prefix-cache + prompt-logprobs case, it would also be beneficial to have only one of the child requests enable prompt logprobs. But maybe that would complicate things slightly when aggregating the outputs so fine to punt on it I think, especially if we're planning to add support for prompt logprobs with APC.

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/async_llm.py
> +            w_sampling_params = parent_state.get_warmup_sampling_params()
I think "prefill" or "priming" instead of "warmup" might be a better term to use for this.

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/async_llm.py
> +                task.cancel()
I think the [`merge_async_generators`](https://github.com/vllm-project/vllm/blob/4c0d93f4b2de241336f4732cb5799cee8fedcb52/vllm/utils.py#L402) util function can be used here.

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +    def transform_output(
IMHO this method is unnecessary .. the code would be simpler and more readable to just include the logic inline.

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +class ParallelSamplingOutputProcessor:
What's the reason for this separate class? Can't `process_output` just be a method on `ParentRequestState`?

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +            return self.parent_state.transform_output(child_req_output, index)
Could simplify the structure a bit here by inverting the if:
```suggestion
        if self.parent_state.output_kind != RequestOutputKind.FINAL_ONLY:
            # stream=true: return child completions immediately
            return self.parent_state.transform_output(child_req_output, index)
            
        # stream=false: aggregate child completions
        self.parent_state.add_output(child_req_output)
        if self.parent_state.num_completions == self.parent_state.n:
            # Return aggregated request output after obtaining
            # all completions
            return self.parent_state.request_output
```

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/async_llm.py
> +    async def _parallel_sampling_child_gen(
Suggest to move this to a method on `ParentRequestState`, it doesn't need to have the `output_processor` arg then either.

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/async_llm.py
> +            async for _ in self._generate(
May be good to do this exhaustion in an async task. Then the subsequent setup can happen in parallel.

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/async_llm.py
> +                    priority,
Best to include kwarg names here `lora_request=lora_request`, etc.

Also could make a dict with the common ones and reuse that below.

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/async_llm.py
> +                seed += 1
Maybe a bit cleaner to just pass the index to this method and handle the seed logic inside.

Actually why not have a single method that returns the child sampling params and request id for given index.

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +        return sampling_params
In the case seed is `None` it would be good to use the same `SamplingParams` object for all children, to avoid cloning it.

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +            # supported for parallel sampling
Is there a way that would make sense to support metrics?

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +            self.request_output.outputs.append(new_completion)
I think we should pass the index into this method and do:
```suggestion
            new_completion.index = index
            self.request_output.outputs[index] = new_completion
```

Of course will need to modify the if body above to to initialize the list to n elements and move the first completion to the correct index.

This is to ensure that the order will be deterministic when using seed.

2025-02-13 00:50 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +        return self.sampling_params.prompt_logprobs
Are these used anywhere?

2025-02-13 08:53 UTC, WoosukKwon commented
@afeldman-nm

> If prefix caching is enabled, an initial warmup request with max_tokens=1 will be sent to the engine to fill the prefix cache.

Why do we need this? V1's prefix caching implementation can deduplicate the prompts even if they are scheduled in the same batch without the warmup.

2025-02-13 11:01 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +            # supported for parallel sampling
@WoosukKwon  @robertgshaw2-redhat thoughts? Is metrics support for parallel sampling a priority?

2025-02-13 11:36 UTC, afeldman-nm commented on vllm/v1/engine/async_llm.py
> +                yield out
Thank you for explaining!

2025-02-13 17:44 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +            # supported for parallel sampling
SGTM, my question wasn't suggesting that should block this PR, just whether it should be something that makes sense to do

2025-02-13 21:12 UTC, m-harmonic commented
> > It seems like this PR is implementing ideas similar to those implemented in PR #9302 for the V0 engine. That PR created some issues that were addressed in PR #11898 and which may exist in the proposed V1 code.
> > In particular, the proposed code currently does not properly handle the case when a seed value is provided for the parent request; the seed value is duplicated in child requests, leading to identical outputs in the child requests. The fix in #11898 was simply to move the copying of the `SamplingParams` object inside a for-loop and to increment the seed value of the parent request.
> > Additionally, the proposed code for the V1 engine defines `get_num_unfinished_requests()` in a way that is currently incompatible with the same function for the V0 engine (though it's really the V0 engine's code which is in the wrong, I am choosing to mention this here as it seems relevant and the PR is still open). In the V0 engine, that function actually counts the number of `SequenceGroup` objects in the engine as opposed to the number of requests. This led to bugs mentioned in Issues #10949 and #11519, and an attempt to fix them is in PR #12428. However, the proposed fix is not compatible with the proposed V1 code. I will comment on that PR as well so that maintainers can adapt the V0 code to align with the proposed V1 code.
> 
> Hi @FrederickVu , thank you for this feedback. I re-implemented this PR from scratch & ensured that if a non-`None` `seed` value is provided to `sampling_params`, then each child request has a different integer seed value (basically what you described - increment `seed` in a loop.)
> 
> As for `get_num_unfinished_requests`, the new implementation of this PR does not rely on this function.

Thanks for working on this. I haven't had a chance to look into the specifics of the new implementation but also wanted to ask about n>1 behavior as this PR (https://github.com/vllm-project/vllm/pull/9302) reduced our throughput by about 3x. It seems that sequence forking was extremely important in the v0 engine. Is an equivalent strategy going to be used in v1? We're now waiting for n>1 support in the v1 engine before we can upgrade past 0.6.3. Thanks

2025-02-13 22:19 UTC, WoosukKwon commented
@m-harmonic

> Thanks for working on this. I haven't had a chance to look into the specifics of the new implementation but also wanted to ask about n>1 behavior as this PR (https://github.com/vllm-project/vllm/pull/9302) reduced our throughput by about 3x. It seems that sequence forking was extremely important in the v0 engine. Is an equivalent strategy going to be used in v1? We're now waiting for n>1 support in the v1 engine before we can upgrade past 0.6.3. Thanks

Thanks for the feedback. I think this is because you didn't add `--enable-prefix-caching`. Starting with the PR you mentioned, vLLM relies on prefix caching to deduplicate the prompts in parallel sampling. As prefix caching is not enabled by default in V0, you may see slowdown if you didn't add `--enable-prefix-caching`. With V1, prefix caching is enabled by default, so you should be able to enjoy the speedup without any extra config.

2025-02-13 22:19 UTC, afeldman-nm commented
> > > It seems like this PR is implementing ideas similar to those implemented in PR #9302 for the V0 engine. That PR created some issues that were addressed in PR #11898 and which may exist in the proposed V1 code.
> > > In particular, the proposed code currently does not properly handle the case when a seed value is provided for the parent request; the seed value is duplicated in child requests, leading to identical outputs in the child requests. The fix in #11898 was simply to move the copying of the `SamplingParams` object inside a for-loop and to increment the seed value of the parent request.
> > > Additionally, the proposed code for the V1 engine defines `get_num_unfinished_requests()` in a way that is currently incompatible with the same function for the V0 engine (though it's really the V0 engine's code which is in the wrong, I am choosing to mention this here as it seems relevant and the PR is still open). In the V0 engine, that function actually counts the number of `SequenceGroup` objects in the engine as opposed to the number of requests. This led to bugs mentioned in Issues #10949 and #11519, and an attempt to fix them is in PR #12428. However, the proposed fix is not compatible with the proposed V1 code. I will comment on that PR as well so that maintainers can adapt the V0 code to align with the proposed V1 code.
> > 
> > 
> > Hi @FrederickVu , thank you for this feedback. I re-implemented this PR from scratch & ensured that if a non-`None` `seed` value is provided to `sampling_params`, then each child request has a different integer seed value (basically what you described - increment `seed` in a loop.)
> > As for `get_num_unfinished_requests`, the new implementation of this PR does not rely on this function.
> 
> Thanks for working on this. I haven't had a chance to look into the specifics of the new implementation but also wanted to ask about n>1 behavior as this PR (#9302) reduced our throughput by about 3x. It seems that sequence forking was extremely important in the v0 engine. Is an equivalent strategy going to be used in v1? We're now waiting for n>1 support in the v1 engine before we can upgrade past 0.6.3. Thanks

Thank you sharing @m-harmonic . This PR's implementation is similar to #9302 ; here, an n>1 request turns into n "child requests" each with n=1. This forking happens outside the engine. #9302 introduced a similar implementation, I believe.

Some immediate questions come to mind - (1) which performance metric(s) are degraded 3x since #9302 ? Time to First Token (i.e. prefill time)? Other metrics? What are your key metrics for your workload? (2) Are you using automatic prefix caching?

2025-02-13 22:20 UTC, WoosukKwon requested changes

2025-02-13 22:20 UTC, WoosukKwon commented on vllm/v1/engine/async_llm.py
> +            w_sampling_params = parent_state.get_warmup_sampling_params()
Again, why do we need this? I think this should be avoided.

2025-02-13 22:41 UTC, m-harmonic commented
> @m-harmonic
> 
> > Thanks for working on this. I haven't had a chance to look into the specifics of the new implementation but also wanted to ask about n>1 behavior as this PR (#9302) reduced our throughput by about 3x. It seems that sequence forking was extremely important in the v0 engine. Is an equivalent strategy going to be used in v1? We're now waiting for n>1 support in the v1 engine before we can upgrade past 0.6.3. Thanks
> 
> Thanks for the feedback. I think this is because you didn't add `--enable-prefix-caching`. Starting with the PR you mentioned, vLLM relies on prefix caching to deduplicate the prompts in parallel sampling. As prefix caching is not enabled by default in V0, you may see slowdown if you didn't add `--enable-prefix-caching`. With V1, prefix caching is enabled by default, so you should be able to enjoy the speedup without any extra config.

Hi thanks for the reply. We did pass `enable_prefix_caching=True` in the engine arguments, which did not affect the throughput. Is there something else we should be doing?

2025-02-14 12:11 UTC, afeldman-nm commented
> > @m-harmonic
> > > Thanks for working on this. I haven't had a chance to look into the specifics of the new implementation but also wanted to ask about n>1 behavior as this PR (#9302) reduced our throughput by about 3x. It seems that sequence forking was extremely important in the v0 engine. Is an equivalent strategy going to be used in v1? We're now waiting for n>1 support in the v1 engine before we can upgrade past 0.6.3. Thanks
> > 
> > 
> > Thanks for the feedback. I think this is because you didn't add `--enable-prefix-caching`. Starting with the PR you mentioned, vLLM relies on prefix caching to deduplicate the prompts in parallel sampling. As prefix caching is not enabled by default in V0, you may see slowdown if you didn't add `--enable-prefix-caching`. With V1, prefix caching is enabled by default, so you should be able to enjoy the speedup without any extra config.
> 
> Hi thanks for the reply. We did pass `enable_prefix_caching=True` in the engine arguments, which did not affect the throughput. Is there something else we should be doing?
> 
> Edit: I got a notification for a comment by @ afeldman-nm but oddly enough it's not showing up now. Per your question, we see the decreased throughput in VLLM's log stats. The number of generated tokens / sec falls from roughly 7k/sec to 2k/sec. In contrast, the prompt throughput rises by about 4-5x. This is for a value of n between 50 and 100. We did have prefix caching enabled in the engine args.

Hi @m-harmonic , sorry I deleted my response because I thought @WoosukKwon 's suggestion to use prefix caching was more relevant, although it appears that that did not resolve the issue. Although, based on the metrics you shared, it sounds like prefix caching is working but the decode throughput is the issue.

2025-02-14 12:28 UTC, afeldman-nm commented on vllm/v1/engine/async_llm.py
> +            w_sampling_params = parent_state.get_warmup_sampling_params()
It appears that the V1 engine can exploit APC against repeated prompts within a batch, without having seen the relevant prompt previously. So it would appear that warmup is not necessary.

2025-02-14 12:42 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +        return self.sampling_params.prompt_logprobs
They were but not anymore. I have removed.

2025-02-14 13:04 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +class ParallelSamplingOutputProcessor:
Agreed, changed.

2025-02-14 13:04 UTC, afeldman-nm commented on vllm/v1/engine/async_llm.py
> +    async def _parallel_sampling_child_gen(
Agreed, done.

2025-02-14 13:06 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +        return sampling_params
@njhill is there a guarantee that it is safe for multiple requests to use the same `SamplingParams` without cloning?

2025-02-14 13:34 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +        return sampling_params
I added a mechanism in the `ParentState` class to cache and reuse the child `sampling_params` over all child requests, *unless* `seed` is not `None` in the parent `sampling_params`

2025-02-14 13:35 UTC, afeldman-nm commented on vllm/v1/engine/async_llm.py
> +                seed += 1
Agreed, done.

2025-02-14 17:56 UTC, m-harmonic commented
> > > @m-harmonic
> > > > Thanks for working on this. I haven't had a chance to look into the specifics of the new implementation but also wanted to ask about n>1 behavior as this PR (#9302) reduced our throughput by about 3x. It seems that sequence forking was extremely important in the v0 engine. Is an equivalent strategy going to be used in v1? We're now waiting for n>1 support in the v1 engine before we can upgrade past 0.6.3. Thanks
> > > 
> > > 
> > > Thanks for the feedback. I think this is because you didn't add `--enable-prefix-caching`. Starting with the PR you mentioned, vLLM relies on prefix caching to deduplicate the prompts in parallel sampling. As prefix caching is not enabled by default in V0, you may see slowdown if you didn't add `--enable-prefix-caching`. With V1, prefix caching is enabled by default, so you should be able to enjoy the speedup without any extra config.
> > 
> > 
> > Hi thanks for the reply. We did pass `enable_prefix_caching=True` in the engine arguments, which did not affect the throughput. Is there something else we should be doing?
> > Edit: I got a notification for a comment by @ afeldman-nm but oddly enough it's not showing up now. Per your question, we see the decreased throughput in VLLM's log stats. The number of generated tokens / sec falls from roughly 7k/sec to 2k/sec. In contrast, the prompt throughput rises by about 4-5x. This is for a value of n between 50 and 100. We did have prefix caching enabled in the engine args.
> 
> Hi @m-harmonic , sorry I deleted my response because I thought @WoosukKwon 's suggestion to use prefix caching was more relevant, although it appears that that did not resolve the issue. Although, based on the metrics you shared, it sounds like prefix caching is working but the decode throughput is the issue.

Thanks @afeldman-nm, appreciate the reply. One thing I'm wondering is whether matching n>1 throughput performance pre-0.6.4 is a priority for this change or follow-up work. It seems like fundamentally this new approach confers lower throughput. Relatedly, is there an architectural reason why this new approach is necessary in v1 or is it possible forking could be added later on if it makes a big difference?

2025-02-18 21:38 UTC, afeldman-nm commented
Merged #13421 (LLMEngine support for parallel sampling) into this PR.

2025-02-18 23:33 UTC, njhill reviewed
Thanks @afeldman-nm for the great work.

I am still reviewing the `llm_engine.py` changes but wanted to post the comments I have so far. I feel like there may still be room to simplify/condense things a bit more, and possibly move more logic out of the main classes.

2025-02-18 23:33 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +        if seed is None and self.cached_child_sampling_params:
nit:
```suggestion
        if self.cached_child_sampling_params:
```

2025-02-18 23:33 UTC, njhill commented on vllm/v1/engine/llm_engine.py
> +                                            self._do_reset_parallel_sampling)
```suggestion
        self._do_reset_parallel_sampling = (num_parallel_reqs > 0 or
                                            self._do_reset_parallel_sampling)
```

2025-02-19 17:42 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +    async def parallel_sampling_child_gen(
Agreed, fixed manually

2025-02-19 18:15 UTC, afeldman-nm commented on vllm/v1/engine/async_llm.py
> +            c_sampling_params = req_mgr.get_child_sampling_params(idx)
Agreed, done

2025-02-19 18:20 UTC, afeldman-nm commented on vllm/v1/engine/llm_engine.py
> +        return len(self.parallel_child_reqs)
Agreed, removed.

2025-02-19 19:22 UTC, afeldman-nm commented on vllm/v1/engine/llm_engine.py
> +    def _add_request_parallel_sampling(
Done.

2025-02-20 00:52 UTC, njhill reviewed
Thanks @afeldman-nm, it's looking much better.

2025-02-20 00:52 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +def add_request_parallel_sampling(
I think this would make more sense as a method on the manager? rather than the manager being passed in

2025-02-20 00:52 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +        c_req_id, c_params = req.get_child_info(idx)
use full names? the `c_` is less readable to me for some reason (and elsewhere)
```suggestion
        child_req_id, child_params = req.get_child_info(idx)
```

2025-02-20 00:52 UTC, njhill commented on vllm/v1/engine/llm_engine.py
> +                              priority=priority)
to simplify the code here, could make a dict of the common kwargs and use that in both the if and the else with **kwargs
```python
kwargs = dict(
    request_id=request_id,
    params=params,
    # ...
```

2025-02-20 00:52 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +                (cdx, req_id) = cdx_req_id
Use clearer var names?
```suggestion
        for output in outputs:
            req_id = output.request_id
            if child_req_entry := self.child_reqs.get(req_id, None):
                # For each parallel sampling child request output:
                index, parent_req_id = child_req_entry
```
...

2025-02-20 00:52 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +            return child_req_output
@afeldman-nm is the v0 behaviour to not aggregate child request outputs into a single RequestOuput at the step level when streaming, even for LLMEngine / sync mode?

2025-02-20 00:52 UTC, njhill commented on vllm/v1/engine/async_llm.py
> +                priority=priority)
Same as other comment here .. could make a dict of the common kwargs to deduplicate.

2025-02-20 00:52 UTC, njhill commented on vllm/v1/engine/async_llm.py
> +            vllm_config.cache_config.enable_prefix_caching)
Is this still needed? It doesn't really look used/related to the other changes

2025-02-20 00:52 UTC, njhill commented on vllm/v1/engine/llm_engine.py
> +        self.parallel_mgr = SyncParallelSamplingManager()
I am sometimes good with abbreviations if it helps to avoid line breaks :)
```suggestion
        self.parallel_manager = SyncParallelSamplingManager()
```

2025-02-20 00:56 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +        self._do_reset = False
As mentioned offline, I think it makes most sense remove the requests from these dicts as they complete (check the `finished` flag in the output, parent is complete once all of it's children are complete), instead of having the reset behaviour.

2025-02-20 01:27 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +                del self.child_reqs[c_req_id]
@njhill where child requests are deleted

2025-02-20 01:27 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +                    del self.parent_reqs[req_id]
@njhill where parent requests are deleted

2025-02-20 01:28 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +                del self.child_reqs[c_req_id]
Thanks, sorry I missed these somehow on the last pass!

2025-02-20 01:30 UTC, njhill commented on vllm/v1/engine/parallel_sampling.py
> +        self._do_reset = False
Sorry, I somehow missed that you weren't already doing that. With that, I don't think any of the reset logic is needed. Since this state will match whatever hasn't yet been returned from the engine.

2025-02-20 17:13 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +            return child_req_output
I had to think for a bit about what you meant, but this is a very good question.

2025-02-20 17:31 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +        c_req_id, c_params = req.get_child_info(idx)
Agreed, fixed manually

2025-02-20 17:34 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +                (cdx, req_id) = cdx_req_id
Agreed, fixed manually.

2025-02-20 19:28 UTC, afeldman-nm commented on vllm/v1/engine/async_llm.py
> +            vllm_config.cache_config.enable_prefix_caching)
Good catch, now that the warmup request is gone, we don't need this.

2025-02-20 19:30 UTC, afeldman-nm commented on vllm/v1/engine/llm_engine.py
> +        self.parallel_mgr = SyncParallelSamplingManager()
Agreed, fixed manually

2025-02-20 21:34 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +            return child_req_output
I tested vLLM v0 through the OpenAI API with `n=20` or something ridiculous like that & I never saw a case where more than one child completion appeared in a given request output. So I am going to proceed (at least for now) as if it does not matter.

2025-02-20 21:38 UTC, afeldman-nm commented on vllm/v1/engine/parallel_sampling.py
> +            return child_req_output
However, I did realize that in the streaming case, the `finished` flag was probably not being set correctly. I modified the stream-mode behavior to count the number of child requests with `finished=True` & only sets `finished=True` in the parent request output once `n` child requests have completed.

The new `ParallelSamplingRequest.process_output()`:

```
    def process_output(
        self,
        child_req_output: RequestOutput,
        index: int,
    ) -> Optional[RequestOutput]:
        if self.output_kind != RequestOutputKind.FINAL_ONLY:
            # stream=true: return child completions immediately
            child_req_output.request_id = self.request_id
            child_req_output.outputs[0].index = index
            if child_req_output.finished:
                # Parent request is complete if all child requests are
                # complete.
                self.num_completions += 1
                child_req_output.finished = (self.num_completions == self.n)
            return child_req_output

        # stream=false: aggregate child completions
        self._add_output(child_req_output, index)
        if self.num_completions == self.n:
            # Return aggregated request output after obtaining
            # all completions
            return self._get_final_request_output()
        return None
```

2025-02-20 23:47 UTC, njhill approved these changes
Thanks @afeldman-nm, let's land this and then @markmc can open a follow-on to refactor.

2025-02-21 17:53 UTC, WoosukKwon approved these changes

2025-02-21 19:02 UTC, WoosukKwon commented
@afeldman-nm could you please check the failed tests and fix or re-run them?

2025-02-24 16:29 UTC, merged