Don't try to add special tokens to the matcher in XGrammar.
vllm-project/vllm pull request #11060
Opened 2024-12-10 09:51 UTC by sjuxax

Prevent XGrammar from attempting to match on special tokens. XGrammar throws the assertion on the C++ side if we send it a special token for acceptance, which crashes the whole engine. This fix uses XGrammar's `tokenizer_info` to skip over these tokens before we submit them and get crashed.

FIX #11044 ; see that issue for the original traceback.

There may be a better way to do this than just continuing over the last token while it's special, but this is sufficient to resolve the crash for me and I'm noticing no slowdown or additional issues in outputs. Thanks!

2024-12-16 08:24 UTC, aarnphm requested changes
My hunch is that this felt like a bit of a hack

@Ubospica is there any specific reason why special tokens will crash the engine here?

2024-12-16 08:24 UTC, aarnphm commented on vllm/model_executor/guided_decoding/xgrammar_decoding.py
> +            assert self.ctx is not None
Hi there, I don't think this assert is necessary.

2024-12-16 08:24 UTC, aarnphm commented on vllm/model_executor/guided_decoding/xgrammar_decoding.py
> +                    if input_ids[
move to under L250 and use sampled_token to avoid additional access here.

2024-12-25 12:16 UTC, Ubospica commented
Hi @sjuxax, I think these special tokens should be forbidden from generated by xgrammar. As I discussed in this [previous comment](https://github.com/vllm-project/vllm/issues/11044#issuecomment-2548356421), could you kindly provide the specific code that caused the error, or the model, prompt, and output structure? I believe by investigating the reasons behind these token generations, we can further resolve the issue.

2025-03-16 14:20 UTC, aarnphm commented
From #14868 xgrammar now can handle special tokens accordingly based on the encoded vocab, which should resolve this issue.

2025-03-16 14:20 UTC, closed without merging