[BugFix] fix wrong output when using lora and num_scheduler_steps=8
vllm-project/vllm pull request #11161
Opened 2024-12-13 06:28 UTC by sleepwalker2017

FIX issue https://github.com/vllm-project/vllm/issues/9688 https://github.com/vllm-project/vllm/issues/11086

2024-12-13 06:32 UTC, sleepwalker2017 commented
@jeejeelee Hi, I've sent a new pr, please help check it.

2024-12-13 16:33 UTC, jeejeelee requested changes
Could you plz add unit test for this，maybe [test_llama_tp ](https://github.com/vllm-project/vllm/blob/main/tests/lora/test_llama_tp.py)is a good choice

2024-12-13 16:33 UTC, jeejeelee commented on vllm/worker/worker.py
> -        if self.model_runner.lora_manager:
We should keep this comment.

2025-01-29 03:40 UTC, jeejeelee approved these changes
Thank your for fixing, LGTM

2025-02-01 04:52 UTC, merged