support shard on more than 8 GPUs for llama2-70b
vllm-project/vllm pull request #1122
Opened 2023-09-21 05:51 UTC by wejoncy

For now Llama2 has only 8 KV head so we can't run Llama2-70b on more than 8 GPUs.

This PR is to support it.

2023-09-23 01:05 UTC, zhuohan123 requested changes
Thanks for your contribution! Please also run the formatter `format.sh` to fix the formatter issue.

2023-09-23 01:05 UTC, zhuohan123 commented on vllm/model_executor/models/llama.py
> +        assert max(self.total_num_kv_heads, tp_size)% min(self.total_num_kv_heads, tp_size) == 0
Could you comment on the logic here?

2023-09-23 01:05 UTC, zhuohan123 commented on vllm/model_executor/models/llama.py
> +        repeat_num = max(1, tp_size//self.total_num_kv_heads)
Nit: naming `repeat_num` -> `num_kv_heads_replicas`

2023-09-23 01:05 UTC, zhuohan123 commented on vllm/model_executor/models/llama.py
> +        assert max(self.total_num_kv_heads, tp_size)% min(self.total_num_kv_heads, tp_size) == 0
A little bit longer but easier to understand:
```suggestion
        if self.total_num_kv_heads >= tp_size:
            assert self.total_num_kv_heads % tp_size == 0
        else:
            assert tp_size % self.total_num_kv_heads == 0
```

2023-09-25 02:43 UTC, wejoncy commented
Hi @zhuohan123 Thanks for your review.
Issues have been fixed.

2023-09-28 05:24 UTC, zhuohan123 commented
@wejoncy Can you enable the edit permission of this PR? I would like to submit some modifications and merge this PR.

2023-09-28 07:46 UTC, wejoncy commented
Hi @zhuohan123 , It's enabled.

Since you created a nother PR, maybe I can close this one.

2023-09-28 23:32 UTC, esmeetu commented
@wejoncy I tried understand this method. The main idea is that if i can't have enough memory with 8 gpus to run whole model with 8 kv keads, we put 8 kv heads onto 16 gpus using two replicas kv heads but split other attention layers as usual？ Only kv layers are duplicated, others are split without duplication. Am i right?

2023-09-29 01:13 UTC, wejoncy commented
> @wejoncy I tried understand this method. The main idea is that if i have not enough memory with 8 gpus to run whole model with 8 kv keads, we can put 8 kv heads onto 16 gpus using two replicas kv heads but split other attention layers as usual？ Only kv layers are duplicated, others are split without duplication. Am i right?

Yes, exactly.

2023-09-29 01:14 UTC, closed without merging