support chatglm3
vllm-project/vllm pull request #1558
Opened 2023-11-04 03:19 UTC by gameofdimension

2023-11-04 04:19 UTC, gameofdimension commented
because the model architecture is the same as chatglm2-6b, so it also works for chatglm2-6b
> Prompt: 'Hello, my name is', Generated text: " Toots. I'm a member of the Hello, Toots community."
> Prompt: 'The president of the United States is', Generated text: '\xa0the head of the executive branch and has the power to make decisions and take'
> Prompt: 'The capital of France is', Generated text: ' In the capital of France, the population is approximately 12 million people.'
> Prompt: 'The future of AI is', Generated text: ' to become more human-like and to be able to perform tasks that currently require'
> Prompt: '希望这篇文章能', Generated text: '您的公司带来新的发展机遇。\n\n'
> Prompt: '给六岁小朋友解释一下万有引', Generated text: '力的概念。 首先，我们需要知道什么是引力。引力是物体之间的相互作用'

2023-11-05 16:40 UTC, cauyxy commented on vllm/model_executor/models/chatglm.py
> +        self.activation_func = swiglu
Maybe use `SiluAndMul` instead
`from vllm.model_executor.layers.activation import SiluAndMul`

2023-11-05 16:57 UTC, cauyxy commented on vllm/model_executor/models/chatglm.py
> +                self.num_heads * self.head_dim,
These variables may be precomputed in __init__() as `q_size, kv_size, kv_size` like llama impl.
`q, k, v = qkv.split([self.q_size, self.kv_size, self.kv_size], dim=-1)`

2023-11-05 17:08 UTC, cauyxy commented on vllm/transformers_utils/configs/chatglm.py
> +from transformers import PretrainedConfig
Add a copyright notice here?
`Copied from xxx` or `Adapted from xxx`

2023-11-05 17:13 UTC, cauyxy commented on vllm/model_executor/models/chatglm.py
> +                self.num_heads * self.head_dim,
`**hidden_states**, _ = self.query_key_value(hidden_states)`

maybe `hidden_states` is not a good variable name to hold the return value

2023-11-06 02:18 UTC, wengyuan722 commented
root@autodl-container-43e51183ae-e83acbf8:~/vllm-main/vllm/entrypoints/openai# python api_server.py --host 127.0.0.1 --port 6006 --model /root/autodl-tmp/chatglm3-6b --trust-remote-code --served-model-name chatglm3-6b --max-num-batched-tokens 8192 --max-model-len 8192
INFO 11-06 10:14:50 llm_engine.py:72] Initializing an LLM engine with config: model='/root/autodl-tmp/chatglm3-6b', tokenizer='/root/autodl-tmp/chatglm3-6b', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
Traceback (most recent call last):
  File "api_server.py", line 623, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/root/miniconda3/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 487, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/root/miniconda3/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 270, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 306, in _init_engine
    return engine_class(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 96, in __init__
    self._verify_args()
  File "/root/miniconda3/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 187, in _verify_args
    self.model_config.verify_with_parallel_config(self.parallel_config)
  File "/root/miniconda3/lib/python3.8/site-packages/vllm/config.py", line 128, in verify_with_parallel_config
    total_num_hidden_layers = self.hf_config.num_hidden_layers
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'ChatGLMConfig' object has no attribute 'num_hidden_layers'

I use openai/api_server.py to start chatglm3-6b api,it return AttributeError: 'ChatGLMConfig' object has no attribute 'num_hidden_layers'

2023-11-06 02:46 UTC, gameofdimension commented
> root@autodl-container-43e51183ae-e83acbf8:~/vllm-main/vllm/entrypoints/openai# python api_server.py --host 127.0.0.1 --port 6006 --model /root/autodl-tmp/chatglm3-6b --trust-remote-code --served-model-name chatglm3-6b --max-num-batched-tokens 8192 --max-model-len 8192 INFO 11-06 10:14:50 llm_engine.py:72] Initializing an LLM engine with config: model='/root/autodl-tmp/chatglm3-6b', tokenizer='/root/autodl-tmp/chatglm3-6b', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0) Traceback (most recent call last): File "api_server.py", line 623, in engine = AsyncLLMEngine.from_engine_args(engine_args) File "/root/miniconda3/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 487, in from_engine_args engine = cls(engine_args.worker_use_ray, File "/root/miniconda3/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 270, in **init** self.engine = self._init_engine(*args, **kwargs) File "/root/miniconda3/lib/python3.8/site-packages/vllm/engine/async_llm_engine.py", line 306, in _init_engine return engine_class(*args, **kwargs) File "/root/miniconda3/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 96, in **init** self._verify_args() File "/root/miniconda3/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 187, in _verify_args self.model_config.verify_with_parallel_config(self.parallel_config) File "/root/miniconda3/lib/python3.8/site-packages/vllm/config.py", line 128, in verify_with_parallel_config total_num_hidden_layers = self.hf_config.num_hidden_layers File "/root/miniconda3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 261, in **getattribute** return super().**getattribute**(key) AttributeError: 'ChatGLMConfig' object has no attribute 'num_hidden_layers'
> 
> I use openai/api_server.py to start chatglm3-6b api,it return AttributeError: 'ChatGLMConfig' object has no attribute 'num_hidden_layers'


maybe you are testing  against a wrong commit

2023-11-06 03:19 UTC, cauyxy commented on vllm/model_executor/models/chatglm.py
> +from typing import List, Optional, Tuple
add a copy right notice here？
and `Inference-only ChatGLM model compatible...` be consistent with other models.

2023-11-06 06:15 UTC, cauyxy reviewed
LGTM. Wait @zhuohan123  take a look at it.

2023-11-06 22:30 UTC, zhuohan123 requested changes
Thank you for your contribution! Left some style comments and I will test the correctness later.

2023-11-06 22:30 UTC, zhuohan123 commented on vllm/config.py
> +        return hf_config.num_hidden_layers
Please remove this function and add the following to `ChatGLMConfig`

```python
    attribute_map = {
        "num_hidden_layers": "num_layers",
    }
```

You can refer to falcon's config: https://github.com/vllm-project/vllm/blob/8516999495114926c9838c2d6e0feb580d4d983f/vllm/transformers_utils/configs/falcon.py#L25-L29

2023-11-06 22:30 UTC, zhuohan123 commented on vllm/model_executor/layers/rotary_embedding.py
> +        is_glm_style: bool = False,
Can you change this to:
```suggestion
        style: str = "neox",
```
and set style to `"neox", "gptj", "glm"` accordingly?

2023-11-06 22:30 UTC, zhuohan123 commented on vllm/model_executor/models/chatglm.py
> +    load_padded_tensor_parallel_vocab
Please use `()` for line continuation:
```suggestion
from vllm.model_executor.weight_utils import (
    hf_model_weights_iterator, load_tensor_parallel_weights, 
    load_padded_tensor_parallel_vocab)
```

2023-11-06 22:30 UTC, zhuohan123 commented on vllm/model_executor/models/chatglm.py
> +        self.total_num_kv_heads, self.num_kv_heads, num_kv_heads_replicas = \
Please use `()` for line continuation.

2023-11-06 22:30 UTC, zhuohan123 commented on vllm/model_executor/layers/attention.py
> +        is_glm_style: bool = False,
Let's use a single style variable:
```suggestion
        style: str = "neox",
```

2023-11-06 22:30 UTC, zhuohan123 commented on vllm/model_executor/models/chatglm.py
> +                total_num_kv_heads, num_kv_heads, num_kv_heads_replicas = \
Please use `()` for line continuation.

2023-11-06 22:30 UTC, zhuohan123 commented on vllm/transformers_utils/configs/chatglm.py
> +        self.apply_residual_connection_post_layernorm = \
Please use `()` for line continuation.

2023-11-07 00:11 UTC, closed without merging

2023-11-07 00:11 UTC, zhuohan123 commented
Again, thank you for your contribution! We merged https://github.com/vllm-project/vllm/pull/1261 and the current main branch supports ChatGLM now. Let us know if the main branch does not look good and feel free to propose any changes!

2023-11-07 03:22 UTC, gameofdimension commented
> Again, thank you for your contribution! We merged #1261 and the current main branch supports ChatGLM now. Let us know if the main branch does not look good and feel free to propose any changes!

pr 1261 might not support tp where world size is bigger than kv heads.

https://github.com/vllm-project/vllm/blob/1a2bbc930135cd3b94fbff2aafbdf5c568acc8bd/vllm/config.py#L171