[Bugfix] Fix the non-blocking behavior of the sampler
vllm-project/vllm pull request #2190
Opened 2023-12-19 03:59 UTC by ZiyueHuang

Cuda-Caching-Allocator in PyTorch relies on the ordering guarantee of the same stream for safe memory reuse (even if the computation is async), but there are no such guarantees for different stream. Note that the sampling tensors are created under `copy_stream` and used in `main_stream`, so `tensor.record_stream` should be called on those tensors for proper synchronization.

Reference:
https://pytorch.org/docs/stable/generated/torch.Tensor.record_stream.html
https://zdevito.github.io/2022/08/04/cuda-caching-allocator.html

cc @Yard1 @WoosukKwon @zhuohan123

2023-12-19 04:18 UTC, Yard1 commented
Thanks, I was not aware of this. This fix looks good to me!

2023-12-19 04:19 UTC, Yard1 approved these changes

2023-12-19 04:22 UTC, Yard1 commented
Actually, should this be called inside the previous stream?

2023-12-19 04:28 UTC, Yard1 commented
@ZiyueHuang Actually could we add a `record_stream` method to SamplingTensors to clean the code up a little?

2023-12-19 04:49 UTC, Yard1 requested changes
Now that I think about it, I think it would be better to preallocate those tensors in the default stream. That way, we should have a guarantee they will never be deallocated. Not sure how feasible that will be, though...

2023-12-19 05:05 UTC, ZiyueHuang commented
@Yard1 There are indeed two ways for multi-stream usage (see https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main_amp.py for example):

- Allocate tensors under another stream and use `record_stream`.
- Allocate tensors under main stream when `record_stream` is not available, but with more care to be taken.

The first way looks standard to me and it is also used other places, e.g., data loader in apex example.

2023-12-19 05:14 UTC, Yard1 commented
Is my understanding correct that this is only an issue if the CPU tensor object is deleted/goes out of scope?

2023-12-19 05:21 UTC, ZiyueHuang commented
Yes, but note that cuda tensors may also get out-of-scope, because the kernels are async.

2023-12-19 05:28 UTC, ZiyueHuang commented
Maybe we also need call `record_stream` on the cpu pin_memory tensors in this case? see `CachingHostAllocator.h` and `PinnedMemoryAllocator.h`.

2023-12-19 05:35 UTC, Yard1 commented
Ah, what I meant is the Python tensor object when I said "CPU". I was under the impression that Pytorch cannot release the memory of a tensor as long as the corresponding Python object is alive. Is that not the case?

2023-12-19 05:49 UTC, ZiyueHuang commented
> Pytorch cannot release the memory of a tensor as long as the corresponding Python object is alive

Yes, you're right.

2023-12-19 06:05 UTC, ZiyueHuang commented
@Yard1  It seems that we don't need worry about the issue of cpu-pinned-memory reuse, see https://github.com/pytorch/pytorch/blob/327bdcdb148bdbb9014030c3913f186b82d197bf/aten/src/ATen/native/cuda/Copy.cu#L340 (CachingHostAllocator_recordEvent is called at end of the copy kernel if non-blocking mode is on).

@esmeetu  Then I don't know what's the cause of the bug in https://github.com/vllm-project/vllm/pull/2177. Maybe not only related to the non-blocking sampler.

2023-12-19 06:57 UTC, hanzhi713 commented
@Yard1 Conceptually, I don't think the sampler code is wrong. There are GPU CPU sync in `_sample`, so the sampler tensors will not go out of scope before the kernel using them finished, and hence their memory should be retained.

2023-12-19 06:59 UTC, Yard1 commented
Exactly, which is why I am confused as to what's happening with @esmeetu's issue in #2177 . I have also been extensively using this and didn't notice any issues. Perhaps it's related to specific order of operations that is only reliably reproducible with certain models/prompts/hardware. Hard to say.

2023-12-20 00:51 UTC, Yard1 commented
@ZiyueHuang @esmeetu I think we could just get rid of the copy stream. It should still be non blocking (the copying will just happen after the forward pass, but that's at worst ~5 microseconds overhead). I will quickly test that.

2023-12-20 02:16 UTC, closed without merging