Changed scheduler to use deques instead of lists
vllm-project/vllm pull request #2290
Opened 2023-12-27 19:38 UTC by NadavShmayo

Currently the scheduler uses lists to store the running, waiting and swapped requests.
When iterating over each state queue we pop the first item and append to a new list, which is not good for performance since each pop is O(N) time complexity, which means the scheduler currently run in O(N^2) time complexity (a pop happens for each item in the state queue).
Instead of using lists we could use deques, since we can pop the first item from a deque in O(1) time complexity, making the scheduler run in O(N) time complexity instead of O(N^2).

I wasn't sure whether I should keep the same types in the SchedulerOutputs class and cast from a deque to a list before returning the result, but since it seems to work with the SchedulerOutputs contains deques instead of lists I decided to change the types.

2024-01-02 17:28 UTC, WoosukKwon requested changes
Hi @NadavShmayo, thanks for submitting the PR! Yes, it seems we should use deque instead of list for the queues in our scheduler. I left some minor comments on the PR. Please take a look at them!

2024-01-02 17:28 UTC, WoosukKwon commented on vllm/core/policy.py
> +    ) -> deque[SequenceGroup]:
nit: Could you use `Deque` in `typing` package for type annotation? Same for other places.
```python
from typing import Deque
```

2024-01-02 17:28 UTC, WoosukKwon commented on vllm/core/scheduler.py
> +from collections import deque
```suggestion
from collections import deque
import enum
import time
from typing import Dict, Iterable, List, Optional, Tuple, Union
```
style nit: Please alphabetically sort the import statements 😄

2024-01-02 17:28 UTC, WoosukKwon commented on vllm/core/scheduler.py
> +            scheduled: deque[SequenceGroup] = deque()
For `ignored_seq_groups` and `scheduled`, we only append new items to them. Why don't we keep using `List` for them?

2024-01-02 17:28 UTC, WoosukKwon commented on vllm/core/scheduler.py
> +            seq_lens: deque[int] = deque()
ditto. Let's keep using `List` here.

2024-01-02 17:28 UTC, WoosukKwon commented on vllm/core/scheduler.py
> +        preempted: deque[SequenceGroup] = deque()
ditto. Let's keep using `List` here.

2024-01-02 17:28 UTC, WoosukKwon commented on vllm/core/scheduler.py
> +            ignored_seq_groups=deque(),
```suggestion
            ignored_seq_groups=[],
```

2024-01-02 17:28 UTC, WoosukKwon commented on vllm/core/scheduler.py
> +                num_batched_tokens = (len(seq_lens) + 1) * max_seq_len
Why do we need this change?

2024-01-02 17:28 UTC, WoosukKwon commented on vllm/core/scheduler.py
> +                                                     num_prompt_tokens)
Why do we need this change?

2024-01-02 17:28 UTC, WoosukKwon commented on vllm/core/scheduler.py
> +                seq_lens.append(num_prompt_tokens)
Why do we need this change?

2024-01-07 17:47 UTC, WoosukKwon approved these changes
LGTM. I've made some minor changes to accelerate the merge. Thanks again for the PR!

2024-01-07 17:48 UTC, merged

2024-01-07 22:00 UTC, NadavShmayo commented
> LGTM. I've made some minor changes to accelerate the merge. Thanks again for the PR!

Hey, sorry for the delayed response.
I didn't get to fixing the code yet, meant to do it tomorrow, but good to see you already did!

Regarding the changes in the `new_seq_lens` logic, I thought it was better this way, instead of creating a new list each time to calculate the total batched tokens which might be slow.
But these are minor changes anyways.

Thanks for the review! 😄