Accelerate LLaMA model loading
vllm-project/vllm pull request #234
Opened 2023-06-25 07:31 UTC by JF-D

This PR is for accelerating LLaMA model weights loading with safetensors. I find current load weight implementation doubles the time cost as the tensor-model parallelism increases (refer to the belowing loading time table for LLaMA-65B).

Parallelism Degree| Original (minutes) | Safetensors (minutes)
---|---|---
1| ~5 | ~5
2| ~10 | ~5
4| ~10 | ~5

I think it is ready for review. 
Code adapted from https://github.com/huggingface/text-generation-inference/blob/v0.8.2/server/text_generation_server/models/flash_llama.py#L206

2023-06-28 17:30 UTC, AlpinDale approved these changes

2023-06-28 17:30 UTC, AlpinDale commented
Oh sorry, didn't mean to do that.

2023-07-12 05:28 UTC, lucasjinreal commented
@AlpinDale Can merge this? Currently model loading are extremly slow

2023-07-18 08:31 UTC, creatorrr commented
@JF-D could you please add some comments to your changes? A tad hard to read them at the moment :grimacing:

2023-07-19 12:25 UTC, JF-D commented
Resolve conflicts for reference.

2023-07-25 21:24 UTC, zhuohan123 requested changes
@JF-D Sorry for the long delay. A lot of people have actually asked for safetensor support and your PR looks great for LLaMA models! Do you think there is a possibility to extend what you did to all models by just modifying the `hf_model_weights_iterator` function?

2023-08-05 07:29 UTC, JF-D commented
@zhuohan123 I think it's possible, and I've updated the `hf_model_weights_iterator` function. Maybe you can review it.

2023-08-16 21:07 UTC, AlpinDale commented on vllm/model_executor/weight_utils.py
> +from safetensors.torch import load_file, save_file
We also want to import `safe_open` from `safetensors.torch` here.

2023-08-22 06:08 UTC, zhuohan123 requested changes
Again, thank you for your great contribution! We tested the code last week and it works great! Left some questions and small suggestions. Once fixed, this PR should be able to be merged. BTW you can run `format.sh --all` to format your changes.

2023-08-22 06:08 UTC, zhuohan123 commented on vllm/model_executor/weight_utils.py
> +    loaded_weight: torch.Tensor or object,
Style nit:
```suggestion
    loaded_weight: Any,  # `torch.Tensor` or `PySafeSlice`
```
If you can find the definition of `PySafeSlice` class, please use `PySafeSlice` here directly.

2023-08-30 07:59 UTC, zhuohan123 approved these changes
Thank you for your contribution again! I will merge this PR first, and then add safetensor loading for other models in another PR.

2023-08-30 08:00 UTC, merged