Sheduler policy to maximaze throughput
vllm-project/vllm pull request #2357
Opened 2024-01-05 22:17 UTC by sh1ng

I noticed that handling Sequences sorted by length gives some performance improvements as we have less percentage of padding tokens. So this PR adds one more policy that makes scheduling less fair by sorting Sequences within acceptable delay. The worst-case scenario is that a seq will not be processed immediately(compared to FIFO), but until all seq in the delay are processed. 
Setting this parameter to 0.1-0.2 may give some thruput improvements when running a web server. And a larger value makes more sense for batch processing. 

All benchmarks are performed on RTX 3090.

fcfs 4aaafdd289f57a82513a7742155e4f1b796c8bdc
```
python benchmarks/benchmark_throughput.py --output-len 64 --num-prompts 1000 --model h2oai/h2ogpt-40
96-llama2-7b-chat --dataset ShareGPT_V3_unfiltered_cleaned_split.json
Namespace(backend='vllm', vllm_scheduler_policy='fcfs', vllm_scheduler_max_delay=0, dataset='ShareGPT_V3_unfiltered_cleaned_split.json', input_len=None, output_len=64, model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='h2oai/h2ogpt-4096-llama2-7b-chat', quantization=None, tensor_parallel_size=1, n=1, use_beam_search=False, num_prompts=1000, seed=0, hf_max_batch_size=None, trust_remote_code=False, max_model_len=None, dtype='auto', enforce_eager=False, swap_space=16)
INFO 01-05 13:17:44 llm_engine.py:73] Initializing an LLM engine with config: model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, enforce_eager=False, seed=0)
INFO 01-05 13:17:48 llm_engine.py:227] # GPU blocks: 1011, # CPU blocks: 2048
INFO 01-05 13:17:53 model_runner.py:403] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 01-05 13:17:53 model_runner.py:407] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode.
INFO 01-05 13:17:56 model_runner.py:449] Graph capturing finished in 4 secs.
Processed prompts: 100%|██████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [02:14<00:00,  7.42it/s]
Throughput: 7.42 requests/s, 2438.76 tokens/s
```

```
python benchmarks/benchmark_throughput.py --output-len 64 --num-prompts 1000 --model h2oai/h2ogpt-4096-llama2-7b-chat --dataset ShareGPT_V3_unfiltered_cleaned_split.json --vllm-scheduler-policy throughput --vllm-scheduler-max-delay 0.1
Namespace(backend='vllm', vllm_scheduler_policy='throughput', vllm_scheduler_max_delay=0.1, dataset='ShareGPT_V3_unfiltered_cleaned_split.json', input_len=None, output_len=64, model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='h2oai/h2ogpt-4096-llama2-7b-chat', quantization=None, tensor_parallel_size=1, n=1, use_beam_search=False, num_prompts=1000, seed=0, hf_max_batch_size=None, trust_remote_code=False, max_model_len=None, dtype='auto', enforce_eager=False, swap_space=16)
INFO 01-05 13:27:41 llm_engine.py:73] Initializing an LLM engine with config: model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, enforce_eager=False, seed=0)
INFO 01-05 13:27:45 llm_engine.py:227] # GPU blocks: 1011, # CPU blocks: 2048
INFO 01-05 13:27:49 model_runner.py:403] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 01-05 13:27:49 model_runner.py:407] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode.
INFO 01-05 13:27:53 model_runner.py:449] Graph capturing finished in 4 secs.
Processed prompts: 100%|██████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [01:53<00:00,  8.83it/s]
Throughput: 8.83 requests/s, 2904.79 tokens/s
```

Setting the delay to `0` means no reordering, but enable SWAP. 
```
python benchmarks/benchmark_throughput.py --output-len 64 --num-prompts 1000 --model h2oai/h2ogpt-4096-llama2-7b-chat --dataset ShareGPT_V3_unfiltered_cleaned_split.json --vllm-scheduler-policy throughput --vllm-scheduler-max-delay 0
Namespace(backend='vllm', vllm_scheduler_policy='throughput', vllm_scheduler_max_delay=0.0, dataset='ShareGPT_V3_unfiltered_cleaned_split.json', input_len=None, output_len=64, model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='h2oai/h2ogpt-4096-llama2-7b-chat', quantization=None, tensor_parallel_size=1, n=1, use_beam_search=False, num_prompts=1000, seed=0, hf_max_batch_size=None, trust_remote_code=False, max_model_len=None, dtype='auto', enforce_eager=False, swap_space=16)
INFO 01-05 13:34:37 llm_engine.py:73] Initializing an LLM engine with config: model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, enforce_eager=False, seed=0)
INFO 01-05 13:34:42 llm_engine.py:227] # GPU blocks: 1011, # CPU blocks: 2048
INFO 01-05 13:34:46 model_runner.py:403] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 01-05 13:34:46 model_runner.py:407] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode.
INFO 01-05 13:34:50 model_runner.py:449] Graph capturing finished in 4 secs.
Processed prompts: 100%|██████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [02:06<00:00,  7.91it/s]
Throughput: 7.91 requests/s, 2601.37 tokens/s
```

A more realistic scenario of handling web requests.
fcfs
```
# python -m vllm.entrypoints.api_server --model h2oai/h2ogpt-4096-llama2-7b-chat --swap-space 16 --disable-log-requests
python benchmarks/benchmark_serving.py --dataset ShareGPT_V3_unfiltered_cleaned_split.json --backend vllm --tokenizer hf-internal-testing/llama-tokenizer --request-rate 100
Namespace(backend='vllm', host='localhost', port=8000, dataset='ShareGPT_V3_unfiltered_cleaned_split.json', tokenizer='hf-internal-testing/llama-tokenizer', best_of=1, use_beam_search=False, num_prompts=1000, request_rate=100.0, seed=0, trust_remote_code=False)
Token indices sequence length is longer than the specified maximum sequence length for this model (3152 > 2048). Running this sequence through the model will result in indexing errors
Total time: 366.12 s
Throughput: 2.73 requests/s
Average latency: 173.05 s
Average latency per token: 0.67 s
Average tokens/s: 1306.1809333710682
Average latency per output token: 4.33 s
Average output tokens/s: 669.5195394394392
```
```
# python -m vllm.entrypoints.api_server --model h2oai/h2ogpt-4096-llama2-7b-chat --swap-space 16 --disable-log-requests --scheduler-policy throughput --scheduler_max_delay 0.0
python benchmarks/benchmark_serving.py --dataset ShareGPT_V3_unfiltered_cleaned_split.json --backend vllm --tokenizer hf-internal-testing/llama-tokenizer --request-rate 100
Namespace(backend='vllm', host='localhost', port=8000, dataset='ShareGPT_V3_unfiltered_cleaned_split.json', tokenizer='hf-internal-testing/llama-tokenizer', best_of=1, use_beam_search=False, num_prompts=1000, request_rate=100.0, seed=0, trust_remote_cod [...]

2024-01-13 08:08 UTC, LiuXiaoxuanPKU requested changes
Thanks for the contribution!! Just some minor comments.

2024-01-13 08:08 UTC, LiuXiaoxuanPKU commented on vllm/config.py
> +        self.max_delay = max_delay
Perhaps a better name for `max_delay` (`order_window` or something similar)?
Could you add comments in the Args for the two new input variables as well?

2024-01-13 08:08 UTC, LiuXiaoxuanPKU commented on vllm/core/scheduler.py
> +            self.waiting = self.policy.sort_by_priority(self.waiting)
Could you add the `if` check to avoid sorting when the policy is `fcfs`? Please also move the Optimization comment to the `if` check.

2024-01-13 08:08 UTC, LiuXiaoxuanPKU commented on vllm/engine/arg_utils.py
> +                            choices=['fcfs', 'throughput'],
Could you give a better name for `throughput`?

2024-01-13 08:08 UTC, LiuXiaoxuanPKU commented on vllm/engine/arg_utils.py
> +                            help='scheduler max delay')
1. change to `--scheduler-max-delay` for consistency
2. could you update the help message indicating that this arg is only valid/used when the policy is `throughput`

2024-01-16 17:08 UTC, sh1ng commented on vllm/core/policy.py
> +        #Copa-pasted from previous implementation
Done

2024-01-16 17:08 UTC, sh1ng commented on vllm/core/policy.py
> +    """Default FIFO Policy"""
Done

2024-01-16 17:08 UTC, sh1ng commented on vllm/core/policy.py
> +        """We can just sort `Deque[SequenceGroup]` by `arrival_time`"""
Done

2024-01-16 17:09 UTC, sh1ng commented on vllm/core/policy.py
> +    """MaxThroughput tries to maximize throughput by reordering incoming requests.
Renamed to `ReorderPolicy`

2024-01-16 17:13 UTC, sh1ng commented
After rebasing on main I start seeing https://github.com/vllm-project/vllm/issues/2350
```
python benchmarks/benchmark_throughput.py --output-len 256 --num-prompts 1000 --model h2oai/h2ogpt-4096-llama2-7b-chat --dataset ShareGPT_V3_unfiltered_cleaned_split.json --vllm-scheduler-policy reorder 
Namespace(backend='vllm', vllm_scheduler_policy='reorder', vllm_scheduler_reorder_window=0, dataset='ShareGPT_V3_unfiltered_cleaned_split.json', input_len=None, output_len=256, model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='h2oai/h2ogpt-4096-llama2-7b-chat', quantization=None, tensor_parallel_size=1, n=1, use_beam_search=False, num_prompts=1000, seed=0, hf_max_batch_size=None, trust_remote_code=False, max_model_len=None, dtype='auto', enforce_eager=False, swap_space=16)
INFO 01-16 09:11:23 llm_engine.py:70] Initializing an LLM engine with config: model='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer='h2oai/h2ogpt-4096-llama2-7b-chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, enforce_eager=False, seed=0)
INFO 01-16 09:11:27 llm_engine.py:294] # GPU blocks: 1011, # CPU blocks: 2048
INFO 01-16 09:11:30 model_runner.py:503] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 01-16 09:11:30 model_runner.py:507] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 01-16 09:11:34 model_runner.py:557] Graph capturing finished in 3 secs.
Processed prompts:   0%|                                                                                    | 1/1000 [00:14<4:01:14, 14.49s/it]Traceback (most recent call last):
  File "/home/sh1ng/dev/vllm/benchmarks/benchmark_throughput.py", line 336, in <module>
    main(args)
  File "/home/sh1ng/dev/vllm/benchmarks/benchmark_throughput.py", line 211, in main
    elapsed_time = run_vllm(
  File "/home/sh1ng/dev/vllm/benchmarks/benchmark_throughput.py", line 113, in run_vllm
    llm._run_engine(use_tqdm=True)
  File "/home/sh1ng/dev/vllm/vllm/entrypoints/llm.py", line 185, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/home/sh1ng/dev/vllm/vllm/engine/llm_engine.py", line 726, in step
    all_outputs = self._run_workers(
  File "/home/sh1ng/dev/vllm/vllm/engine/llm_engine.py", line 896, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/sh1ng/miniconda3/envs/vllm-py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sh1ng/dev/vllm/vllm/worker/worker.py", line 191, in execute_model
    self.cache_swap(*block_swapping_info)
  File "/home/sh1ng/dev/vllm/vllm/worker/worker.py", line 147, in cache_swap
    self.cache_engine.swap_in(blocks_to_swap_in)
  File "/home/sh1ng/dev/vllm/vllm/worker/cache_engine.py", line 131, in swap_in
    self._swap(self.cpu_cache, self.gpu_cache, src_to_dst)
  File "/home/sh1ng/dev/vllm/vllm/worker/cache_engine.py", line 123, in _swap
    cache_ops.swap_blocks(src_key_cache, dst_key_cache, src_to_dst)
RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED at "/tmp/pip-build-env-zh1rpbon/overlay/lib/python3.10/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h":25, please report a bug to PyTorch. 
Processed prompts:   4%|██▉
```

It's related to using `SWAP` not `RECOMPUTE`.

2024-01-16 20:22 UTC, LiuXiaoxuanPKU commented
If you use the FCFS policy, does the error show up?

2024-01-16 20:23 UTC, LiuXiaoxuanPKU commented on vllm/core/policy.py
> +    def get_preemption_mode(self, seq_group: SequenceGroup) -> PreemptionMode:
Could add comments here, basically explaining RECOMPUTE might not bring benefits here, therefore omitted.

2024-01-16 21:40 UTC, sh1ng commented
@LiuXiaoxuanPKU yes it does, if you change https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py#L373  `preemption_mode = PreemptionMode.RECOMPUTE` to`preemption_mode = PreemptionMode.SWAP` you will see it.

I guess in https://github.com/vllm-project/vllm/issues/2350 the else branch was used.

2024-01-19 21:30 UTC, mohit-paliwal-infrrd commented
@sh1ng any solution for the issue mentioned in #2350?

2024-01-20 15:03 UTC, sh1ng commented on vllm/core/policy.py
> +    def get_preemption_mode(self, seq_group: SequenceGroup) -> PreemptionMode:
Done

2024-01-23 19:14 UTC, iNeil77 commented
@sh1ng is there any workaround for #2350 ? I am facing it too

2024-01-23 21:31 UTC, LiuXiaoxuanPKU commented
Could you share the amount of CPU memory? It might be due to OOM of CPU memory, but I need to reproduce for confirmation.

2024-01-24 00:42 UTC, iNeil77 commented
I have 64GB RAM and I got this error when I set the CPU swap size to 32GB. I believe that really should be enough.

2024-01-24 13:07 UTC, sh1ng commented
I have > 200GB RAM and RTX 3090 with 24GB
```
cat /proc/meminfo
MemTotal:       263859340 kB
```
I guess it's related to the amount of GRAM as it works when using `facebook/opt-125m`.

2024-01-24 14:49 UTC, sh1ng commented
This commit 77af974b406f0947d5eb0b55f7ac4dd4516c38e3 added the bug.

2024-01-26 08:07 UTC, LiuXiaoxuanPKU approved these changes
Thanks for the work!! Just some final comments, we can merge after the fix.

2024-01-26 08:07 UTC, LiuXiaoxuanPKU commented on vllm/core/scheduler.py
> +            # Optimization: We do not sort the waiting queue when use FCFS policy since the preempted
```suggestion
            # Optimization: We do not sort the waiting queue when using FCFS policy since the preempted
```

2024-01-26 08:12 UTC, WoosukKwon commented
BTW, can we have a better name than `reorder` policy? The name itself sounds pretty unclear to me.

2024-01-26 12:05 UTC, sh1ng commented
We can use `out-of-order` or `dynamic` execution policy referring to some extent to the appropriate paradigm in CPU design.

2024-01-26 12:57 UTC, sh1ng commented
Rerun after rebasing on 5265631d15d59735152c8b72b38d960110987f10

`python benchmarks/benchmark_throughput.py --output-len 64 --num-prompts 1000 --model h2oai/h2ogpt-40
96-llama2-7b-chat --dataset ShareGPT_V3_unfiltered_cleaned_split.json`
| Policy | Throughput, tokens/s |
| ----------- | ----------- |
| fcfs | 2417  |
| reorder(reorder-window=0) | 2626 | 
| reorder(reorder-window=0.1) | 2865 |

`python benchmarks/benchmark_serving.py --dataset ShareGPT_V3_unfiltered_cleaned_split.json --backend vllm --tokenizer hf-internal-testing/llama-tokenizer --request-rate 100`
| Policy | Average output tokens/s|
| ----------- | ----------- |
| fcfs | 663  |
| reorder(reorder-window=0) | 717 | 
| reorder(reorder-window=0.1) | 725 |

2024-01-28 08:31 UTC, LiuXiaoxuanPKU commented
1. `order-by-len` sounds a bit more clear. @WoosukKwon What do you think?
2. When testing locally, I found [this line](https://github.com/sh1ng/vllm/blob/bab00a62e9e151910d76ed6656dda946afad9e75/vllm/core/policy.py#L72) requires python >= 3.10 because of the `key` keyword. Currently, vllm does not have any Python requirements. Check with @WoosukKwon @zhuohan123 if we can introduce the requirement, or we can change the way of implementation here.

2024-01-28 09:08 UTC, LiuXiaoxuanPKU commented
A bit more results on A100-80G, 7B model with shareGPT dataset using `benchmark_throughput.py`:
|  Policy | Average output tokens/s |
| -- | -- |
| fcfs | 7620.47 |
| reorder(reorder-window=0) |  7553.19 |
| reorder(reorder-window=0.1) | 8375.41 |

2024-01-29 14:54 UTC, sh1ng commented
@LiuXiaoxuanPKU the results are interesting and show that different hardware has different copying/computational ratios and that affects the best strategy. 

I still consider this code as the very first step to squeeze maximum performance by tuning execution scheduling. We can also invoke multiple kernels in parallel (for long and short sequences) or propose another heuristics that may work better. Should all these tiny details be described by a policy name? Or we can keep the name a bit common and explain all the details in the documentation.

Ok, I'll work on fixing CI.

2024-02-28 17:55 UTC, sh1ng commented
`python benchmarks/benchmark_throughput.py --output-len 64 --num-prompts 1000 --model h2oai/h2ogpt-4096-llama2-7b-chat --dataset ShareGPT_V3_unfiltered_cleaned_split.json`

 Policy | Throughput, tokens/s |
| ----------- | ----------- |
| fcfs | 2439  |
| reorder(reorder-window=0) | 2628 | 
| reorder(reorder-window=0.1) | 2628 |


`python benchmarks/benchmark_serving.py --dataset ShareGPT_V3_unfiltered_cleaned_split.json --backend vllm --tokenizer hf-internal-testing/llama-tokenizer --request-rate 100`
 
fcfs 
```
Successful requests: 1000
Benchmark duration: 367.097980 s
Total input tokens: 248339
Total generated tokens: 241542
Request throughput: 2.72 requests/s
Input token throughput: 676.49 tokens/s
Output token throughput: 657.98 tokens/s
Mean TTFT: 155780.03 ms
Median TTFT: 155800.81 ms
P99 TTFT: 332490.33 ms
Mean TPOT: 4079.64 ms
Median TPOT: 876.44 ms
P99 TPOT: 33485.87 ms 
```

reorder(reorder-window=0) 
```
Successful requests: 1000
Benchmark duration: 335.593543 s
Total input tokens: 248339
Total generated tokens: 241517
Request throughput: 2.98 requests/s
Input token throughput: 740.00 tokens/s
Output token throughput: 719.67 tokens/s
Mean TTFT: 139898.26 ms
Median TTFT: 139223.71 ms
P99 TTFT: 300581.55 ms
Mean TPOT: 3655.94 ms
Median TPOT: 788.52 ms
P99 TPOT: 30211.33 ms
```

reorder(reorder-window=0.1)
```
Successful requests: 1000
Benchmark duration: 331.741561 s
Total input tokens: 248339
Total generated tokens: 241543
Request throughput: 3.01 requests/s
Input token throughput: 748.59 tokens/s
Output token throughput: 728.11 tokens/s
Mean TTFT: 138218.78 ms
Median TTFT: 137750.83 ms
P99 TTFT: 295536.97 ms
Mean TPOT: 3629.72 ms
Median TPOT: 767.92 ms
P99 TPOT: 30055.68 ms
```

2024-03-04 17:51 UTC, sh1ng commented
@LiuXiaoxuanPKU please help me to get it merged.

2024-03-07 16:52 UTC, sh1ng commented
@tdoublep I changed `PreemptionMode` from `RECOMPUTE` to always `SWAP`. And when `scheduler_reorder_window=0` it's  FCFS with `SWAP`. Results depend on the hardware and the model. For RTX 3090 `SWAP` works better while on A100 `RECOMPUTE` wins https://github.com/vllm-project/vllm/pull/2357#issuecomment-1913525320.

I still consider this PR as the very beginning of well optimized and advanced scheduler. Another idea could be to steal requests from the rest of the queue with the same length or keep multiple buckets(by length) and schedule them separately. But the logic should not be too expensive.

FYI https://github.com/vllm-project/vllm/issues/1562

2024-03-07 17:55 UTC, tdoublep commented
@sh1ng got it. I missed the `SWAP` vs. `RECOMPUTE` part, thanks for clarifying.

2024-03-13 08:03 UTC, LiuXiaoxuanPKU commented
Hi @sh1ng, sorry for the very late reply. The team actually discussed about this PR. We are currently a bit concerned about merging it because we feel the major performance benefits come from reducing padding. However, since we are working on chunked prefill ([RFC](https://github.com/vllm-project/vllm/issues/3130)), we expect padding will be greatly reduced. Chunked prefill will flatten input queries into 1D, which only introduces minimum padding.
Do we miss anything here? We'd love to hear your thoughts on this.

2024-04-08 09:04 UTC, AaronFriel commented
@sh1ng Hey, I just want to double check the units here, as these numbers seem a might higher than I see in testing today:

```
Successful requests: 1000
Benchmark duration: 331.741561 s
Total input tokens: 248339
Total generated tokens: 241543
Request throughput: 3.01 requests/s
Input token throughput: 748.59 tokens/s
Output token throughput: 728.11 tokens/s
Mean TTFT: 138218.78 ms
Median TTFT: 137750.83 ms
P99 TTFT: 295536.97 ms
Mean TPOT: 3629.72 ms
Median TPOT: 767.92 ms
P99 TPOT: 30055.68 ms
```

I see a benchmark duration of 331s, but a median "time to first token" of 137 seconds - did half of requests take over 2 minutes to see a token? Should that be microseconds? 

Likewise, TPOT doesn't track with 728.11 tokens/s, is that unit also microseconds?

2025-02-17 17:22 UTC, hmellor commented
I'm assuming this is too stale to merge now. If I'm wrong, feel free to re-open and rebase.

2025-02-17 17:22 UTC, closed without merging