Raise error for long prompt
vllm-project/vllm pull request #273
Opened 2023-06-27 04:47 UTC by LiuXiaoxuanPKU

This is a fix for  #113. The program hangs when the input prompt is too long because [the check ](https://github.com/vllm-project/vllm/blob/43710e8d0965d616db51639ced76605dee1bde93/vllm/core/scheduler.py#L196) will always succeed and the request will always in the waiting queue and will never be added to the running queue. 
Add a check before the if statement, if the prompt length is too long, it will raise ValueError directly.

2023-06-27 16:03 UTC, zhuohan123 commented
Hi Lily, please check all the possible situations [here](https://github.com/vllm-project/vllm/issues/113#issuecomment-1609806237) and make sure you can handle all of them. Thanks!

2023-06-28 03:54 UTC, LiuXiaoxuanPKU commented
I move forward with the length check. The original code should already handle the `len(prompt) + len(generated) > limit` case, so I only deal with `model limit` and `len(prompt) > limit`.  Let me know if there are any problems, thanks!

2023-06-30 21:28 UTC, zhuohan123 requested changes
Hey Lily, thanks for the work! Please check my comments.

2023-06-30 21:28 UTC, zhuohan123 commented on vllm/config.py
> +        max_prompt_len: Maximum length of input prompt.
The actual limit should not be `max_prompt_len`. Actually, it should be `max_sequence_len` that is applied to the sum of the prompt length and the generated output length.  Can you add `max_sequence_len` check also for the sum? Thanks!

2023-07-01 00:35 UTC, zhuohan123 approved these changes
Thanks for the hard work! In general LGTM! Will merge it after the following small comments are fixed.

2023-07-01 00:35 UTC, zhuohan123 commented on vllm/engine/llm_engine.py
> +                if seq.get_len() == \
Please use `()` for line continuation: https://google.github.io/styleguide/pyguide.html#32-line-length

2023-07-01 00:35 UTC, zhuohan123 commented on vllm/engine/llm_engine.py
> +                if seq.get_len() == \
Nit:
```suggestion
                if seq.get_len() >= \
```

2023-07-01 00:35 UTC, zhuohan123 commented on vllm/config.py
> +        self.max_sequence_len = max_sequence_len
Nit: `max_sequence_len` -> `max_seq_len`

2023-07-01 01:48 UTC, merged