GPTQ Fused MOE
vllm-project/vllm pull request #2761
Opened 2024-02-05 14:24 UTC by chu-tianxiang

Thanks to the very smart MoE align strategy introduced in #2453, each block only uses a single expert, making it much easier to be adapted to quantized methods. This PR refactors the code to support quantized fused-MoE and adds GPTQ group gemm kernels based on exllamav2.

tokens/s measured at A100 using `benchmark_latency.py`  with input_len=256 and output_len=1024
| Batch size | 1 | 4 | 16 | 64 | 256 |
|-------|-------|-------|-------|-------|-------|
| main | 38 |  102 | 180 | 343 | 865 |
| pr | 104 | 221 | 424 |  596 | 1109 |

Todo:
- [ ] Support Deepseek MoE
- [ ] Support AWQ via repacking

2024-02-05 21:29 UTC, casper-hansen commented
@chu-tianxiang Great job on optimizing GPTQ! Is there another option than repacking for AWQ?

2024-02-06 05:25 UTC, chu-tianxiang commented
> @chu-tianxiang Great job on optimizing GPTQ! Is there another option than repacking for AWQ?

I can implement the AWQ kernel based on current AWQ gemm implementation too. Which do you think is better?

2024-02-06 07:35 UTC, casper-hansen commented
> > @chu-tianxiang Great job on optimizing GPTQ! Is there another option than repacking for AWQ?
> 
> I can implement the AWQ kernel based on current AWQ gemm implementation too. Which do you think is better?

I would prefer it if you can base it on the current AWQ GEMM kernel

2024-02-07 06:04 UTC, chu-tianxiang commented
> > > @chu-tianxiang Great job on optimizing GPTQ! Is there another option than repacking for AWQ?
> > 
> > 
> > I can implement the AWQ kernel based on current AWQ gemm implementation too. Which do you think is better?
> 
> I would prefer it if you can base it on the current AWQ GEMM kernel

I have updated the AWQ kernels.  AWQ GEMM uses tensor cores and has better performance at large batch size, which turns out to be better suited in the MoE case.

2024-02-07 07:17 UTC, casper-hansen commented
This is excellent work! Looking forward to seeing this merged for a big speedup.

2024-02-14 21:40 UTC, casper-hansen commented
@chu-tianxiang On a side note, I tried importing the kernels from here to AutoAWQ and I am getting CUDA illegal memory access on multi-GPU while it works fine on a single GPU. It triggers at `awq_group_gemm`, which usually means the operation before (`moe_align_block_size`) had some illegal memory access operation.

However, I do not get the same issue in vLLM. Do you have any way or idea to address this issue for AutoAWQ?

2024-02-15 02:13 UTC, chu-tianxiang commented
> @chu-tianxiang On a side note, I tried importing the kernels from here to AutoAWQ and I am getting CUDA illegal memory access on multi-GPU while it works fine on a single GPU. It triggers at `awq_group_gemm`, which usually means the operation before (`moe_align_block_size`) had some illegal memory access operation.
> 
> However, I do not get the same issue in vLLM. Do you have any way or idea to address this issue for AutoAWQ?

Could you please provide the branch / code to reproduce please? vLLM use separate process for tensor parallel while AutoAWQ and transformers use torch hooks for pipeline parallel. An initial guess is that `moe_align_block_size` not using  device guard might be a problem.

2024-02-15 17:41 UTC, casper-hansen commented
Hi @chu-tianxiang, I added an issue to track it. I attempted to put a device guard in place and it fixes the illegal memory access error, but then results in the generated output being garbage. See details in the issue below.

https://github.com/casper-hansen/AutoAWQ/issues/341

2024-02-23 09:56 UTC, casper-hansen commented
@lroberts7 it seems your tests are failing for reasons unrelated to this PR. I think you may have an environment issue or some problem with the GPUs.

2024-02-23 10:11 UTC, chu-tianxiang commented
The PR breaks the mixtral unit test previously and I pushed a fix for it, but I'm still seeing `illegal memory access` in the [CI test](https://buildkite.com/vllm/ci/builds/1578#018dd49d-ec7f-4013-b9ab-7962be808b99) after the commit. I'm not sure what the problem is yet, I pulled the docker image built in CI and cannot reproduce the problem running locally.

2024-02-23 10:20 UTC, casper-hansen commented
> The PR breaks the mixtral unit test previously and I pushed a fix for it, but I'm still seeing `illegal memory access` in the [CI test](https://buildkite.com/vllm/ci/builds/1578#018dd49d-ec7f-4013-b9ab-7962be808b99) after the commit. I'm not sure what the problem is yet, I pulled the docker image built in CI and cannot reproduce the problem running locally.

A few things to try:
- merge with latest main branch
- add CUDAGuard to make sure it's not the source of error

```
    const at::cuda::OptionalCUDAGuard device_guard_topk_ids(device_of(topk_ids));
    const at::cuda::OptionalCUDAGuard device_guard_sorted(device_of(sorted_token_ids));
    const at::cuda::OptionalCUDAGuard device_guard_experts(device_of(experts_ids));
    const at::cuda::OptionalCUDAGuard device_guard_num_tokens(device_of(num_tokens_post_pad));
```

Otherwise, I think we may need insight from @WoosukKwon since you pulled the same image as the CI.

2024-02-23 15:00 UTC, lroberts7 commented
it seems that there are still some of the tests using `get_tensor_model_parallel_group()` that are still executed despite me setting `CUDA_VISIBLE_DEVICES=0` which IIUC would result in no parallel group being set, is there a flag or a way to turn those tests off requiring TP>1? 

If this is a known issue I can go through and add some pytest markers for the tests I'm seeing fail in a separate PR.  

Also, there are some tests that are failing for numerical issues here is one example from the overnight test harness execution: 

```bash
m = 33, n = 1024, k = 1024, e = 64, topk = 6, dtype = torch.bfloat16                                                                                                                               
                                                                                                                                                                                                   
    @pytest.mark.parametrize("m", [512, 222, 33, 1])                                                                                                                                               
    @pytest.mark.parametrize("n", [2048, 256, 1024])                                                                                                                                               
    @pytest.mark.parametrize("k", [128, 511, 1024])                                                                                                                                                
    @pytest.mark.parametrize("e", [8, 64])                                                                                                                                                         
    @pytest.mark.parametrize("topk", [2, 6])                                                                                                                                                       
    @pytest.mark.parametrize("dtype", [torch.float16, torch.bfloat16])                                                                                                                             
    def test_fused_moe(                                                                                                                                                                            
        m: int,                                                                                                                                                                                    
        n: int,                                                                                                                                                                                    
        k: int,                                                                                                                                                                                    
        e: int,                                                                                                                                                                                    
        topk: int,                                                                                                                                                                                 
        dtype: torch.dtype,                                                                                                                                                                        
    ):                                                                                                                                                                                             
        a = torch.randn((m, k), device='cuda', dtype=dtype) / 10                                                                                                                                   
        w1 = torch.randn((e, 2 * n, k), device='cuda', dtype=dtype) / 10                                                                                                                           
        w2 = torch.randn((e, k, n), device='cuda', dtype=dtype) / 10                                                                                                                               
                                                                                                                                                                                                   
        score = torch.randn((m, e), device='cuda', dtype=dtype)                                                                                                                                    
        triton_output = fused_moe(a, w1, w2, score, topk, renormalize=False)                                                                                                                       
        torch_output = torch_moe(a, w1, w2, score, topk)                                                                                                                                           
>       assert torch.allclose(triton_output, torch_output, atol=1e-2, rtol=0)                                                                                                                      
E       AssertionError: assert False                                                                                                                                                               
E        +  where False = <built-in method allclose of type object at 0x7fc71830dd80>(tensor([[-8.1055e-02,  6.9885e-03, -7.7148e-02,  ..., -2.4292e-02,\n          1.8433e-02, -7.9956e-03],\n    
    [-4.711...6.1951e-03,  3.2715e-02,  ...,  1.4771e-02,\n         -2.8564e-02,  3.0762e-02]], device='cuda:0', dtype=torch.bfloat16), tensor([[-1.0193e-02,  1.0986e-02, -3.6621e-03,  ...,  8.91
11e-03,\n          3.5706e-03,  5.2795e-03],\n        [ 2.990...8.0109e-04, -1.5488e-03,  ..., -2.2411e-04,\n          1.3962e-03, -8.6427e-06]], device='cuda:0', dtype=torch.bfloat16), atol=0.01
, rtol=0)                                                                                                                                                                                          
E        +    where <built-in method allclose of type object at 0x7fc71830dd80> = torch.allclose                                                                                                   
                                                                                                                                                                                                   
tests/kernels/test_moe.py:60: AssertionError                         
```

2024-02-23 23:34 UTC, lroberts7 commented
> @lroberts7 it seems your tests are failing for reasons unrelated to this PR. I think you may have an environment issue or some problem with the GPUs.

Thanks for taking a look @casper-hansen I installed the cupy dependency and am rerunning the tests overnight tonight. I'll check in tomorrow and see what the harness run shows. 

If you're referring to something other than the  `ImportError (libnccl.so.2: cannot open shared object file: No such file or directory)` warning that was shown in the later update, then please let me know.

2024-02-26 15:53 UTC, lroberts7 commented
Between the latest push and the cupy update that the warning in my previous execution gave it seems that the tests are all passing for me on A100. Details inside fold out: 

<details>

<summary> pytest output for parallel </summary>

```bash
____________________________________________________________________________________ test_mixtral_moe[dtype0] _____________________________________________________________________________________

dtype = torch.float32

    @pytest.mark.parametrize("dtype",
                             [torch.float32, torch.float16, torch.bfloat16])
    @torch.inference_mode()
    def test_mixtral_moe(dtype: torch.dtype):
        "Make sure our Mixtral MoE implementation agrees with the one from huggingface."
     
        # Instantiate our and huggingface's MoE blocks
        config = MixtralConfig()
        hf_moe = MixtralSparseMoeBlock(config).to(dtype).to("cuda")
>       vllm_moe = MixtralMoE(
            num_experts=config.num_local_experts,
            top_k=config.num_experts_per_tok,
            hidden_size=config.hidden_size,
            intermediate_size=config.intermediate_size,
            params_dtype=dtype,
            tp_size=1,
        ).cuda()

tests/kernels/test_moe.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
vllm/model_executor/models/mixtral.py:114: in __init__
    self.rank = get_tensor_model_parallel_rank()
vllm/model_executor/parallel_utils/parallel_state.py:148: in get_tensor_model_parallel_rank
    return torch.distributed.get_rank(group=get_tensor_model_parallel_group())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def get_tensor_model_parallel_group():
        """Get the tensor model parallel group the caller rank belongs to."""
>       assert _TENSOR_MODEL_PARALLEL_GROUP is not None, (
            "tensor model parallel group is not initialized")
E       AssertionError: tensor model parallel group is not initialized

vllm/model_executor/parallel_utils/parallel_state.py:122: AssertionError
____________________________________________________________________________________ test_mixtral_moe[dtype1] _____________________________________________________________________________________

dtype = torch.float16

    @pytest.mark.parametrize("dtype",
                             [torch.float32, torch.float16, torch.bfloat16])
    @torch.inference_mode()
    def test_mixtral_moe(dtype: torch.dtype):
        "Make sure our Mixtral MoE implementation agrees with the one from huggingface."
     
        # Instantiate our and huggingface's MoE blocks
        config = MixtralConfig()
        hf_moe = MixtralSparseMoeBlock(config).to(dtype).to("cuda")
>       vllm_moe = MixtralMoE(
            num_experts=config.num_local_experts,
            top_k=config.num_experts_per_tok,
            hidden_size=config.hidden_size,
            intermediate_size=config.intermediate_size,
            params_dtype=dtype,
            tp_size=1,
        ).cuda()

tests/kernels/test_moe.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
vllm/model_executor/models/mixtral.py:114: in __init__
    self.rank = get_tensor_model_parallel_rank()
vllm/model_executor/parallel_utils/parallel_state.py:148: in get_tensor_model_parallel_rank
    return torch.distributed.get_rank(group=get_tensor_model_parallel_group())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def get_tensor_model_parallel_group():
        """Get the tensor model parallel group the caller rank belongs to."""
>       assert _TENSOR_MODEL_PARALLEL_GROUP is not None, (
            "tensor model parallel group is not initialized")
E       AssertionError: tensor model parallel group is not initialized

vllm/model_executor/parallel_utils/parallel_state.py:122: AssertionError
____________________________________________________________________________________ test_mixtral_moe[dtype2] _____________________________________________________________________________________

dtype = torch.bfloat16

    @pytest.mark.parametrize("dtype",
                             [torch.float32, torch.float16, torch.bfloat16])
    @torch.inference_mode()
    def test_mixtral_moe(dtype: torch.dtype):
        "Make sure our Mixtral MoE implementation agrees with the one from huggingface."
     
        # Instantiate our and huggingface's MoE blocks
        config = MixtralConfig()
        hf_moe = MixtralSparseMoeBlock(config).to(dtype).to("cuda")
>       vllm_moe = MixtralMoE(
            num_experts=config.num_local_experts,
            top_k=config.num_experts_per_tok,
            hidden_size=config.hidden_size,
            intermediate_size=config.intermediate_size,
            params_dtype=dtype,
            tp_size=1,
        ).cuda()

tests/kernels/test_moe.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
vllm/model_executor/models/mixtral.py:114: in __init__
    self.rank = get_tensor_model_parallel_rank()
vllm/model_executor/parallel_utils/parallel_state.py:148: in get_tensor_model_parallel_rank
    return torch.distributed.get_rank(group=get_tensor_model_parallel_group())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def get_tensor_model_parallel_group():
        """Get the tensor model parallel group the caller rank belongs to."""
>       assert _TENSOR_MODEL_PARALLEL_GROUP is not None, (
            "tensor model parallel group is not initialized")
E       AssertionError: tensor model parallel group is not initialized

vllm/model_executor/parallel_utils/parallel_state.py:122: AssertionError
```

(Maybe @simon-mo has input?)  should these probably be skipped? I can open a PR to add some test skips if you agree.  
</details>

Also, there are some tests that are failing for numerical issues here is one example from the overnight test harness execution: 

<details>
<summary>pytest output for  `tests/kernel` on latest commit of this PR </summary>
```bash
lroberts@GPU77B9:~/update-vllm-env/vllm-source/vllm$ CUDA_VISIBLE_DEVICES=7 python3.10 -m pytest tests/kernels/ --durations=10 
======================================================================================= test session starts =======================================================================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.3.0
rootdir: /home/lroberts/update-vllm-env/vllm-source/vllm
plugins: asyncio-0.23.3, forked-1.6.0, anyio-3.7.1
asyncio: mode=strict
collected 3298 items                                                                                                                                                                              

tests/kernels/test_activation.py ............................................................................................................                                               [  3%]
tests/kernels/test_attention.py ........................................................................................................................................................... [  7%]
......................................................................................................................................................... [...]

2024-02-29 06:36 UTC, chu-tianxiang commented
@WoosukKwon  Since [3&8-bit GPTQ support](https://github.com/vllm-project/vllm/pull/2330#event-11961017720) is merged prior to this PR, this needs quite some modifications to extend to those bits as well. What's your thoughts on whether we should support the 4-bit first or wait all modifications are done?

2024-02-29 06:40 UTC, WoosukKwon commented
@chu-tianxiang Thanks for letting me know! I think we should focus on the 4-bit support in this PR and work on the other bit widths in the future PRs. Could you please update the current PR accordingly?

2024-02-29 11:18 UTC, chu-tianxiang commented
> @chu-tianxiang Thanks for letting me know! I think we should focus on the 4-bit support in this PR and work on the other bit widths in the future PRs. Could you please update the current PR accordingly?

I've pushed a commit fixing the conflicts. Now 4-bit gptq uses fused kernel while other bits still use expert parallel.

2024-03-04 19:24 UTC, WoosukKwon commented
@robertgshaw2-neuralmagic Please take a look at the PR!

2024-03-20 14:06 UTC, CrisRodriguez commented
> Thanks to the very smart MoE align strategy introduced in #2453, each block only uses a single expert, making it much easier to be adapted to quantized methods. This PR refactors the code to support quantized fused-MoE and adds GPTQ group gemm kernels based on exllamav2.
> 
> tokens/s of Mixtral measured at A100 using `benchmark_latency.py` with input_len=256 and output_len=1024.
> 
> * GPTQ:
> 
> Batch size	1	4	16	64	256
> main	38	99	176	341	846
> pr	100	207	395	556	1092
> * AWQ:
> 
> Batch size	1	4	16	64	256
> main	20	77	255	452	533
> pr	71	183	474	1003	1207
> Todo:
> 
> * [x]  Support Deepseek MoE
> * [x]  Support AWQ ~via repacking~
> * [x]  Add tests

Hi @chu-tianxiang,

Hi !

Do you have any idea on why AWQ is (for small batches) slower than GPTQ for Mixtral?

Thanks,

2024-03-21 04:25 UTC, chu-tianxiang commented
@CrisRodriguez  The speed difference is not limited to MoE models. Current GPTQ kernel in vLLM is mostly a GEMV kernel optimized for low batch size while the AWQ kernel is a GEMM kernel optimized for higher batch size.

Better kernels are being introduced for both GPTQ and AWQ like Marlin and the AWQ Fast-GEMV, which are fast across all batch sizes. If those could be adapted to MoE models, we'll see more improvements.

2024-03-21 18:52 UTC, CrisRodriguez commented
> @CrisRodriguez The speed difference is not limited to MoE models. Current GPTQ kernel in vLLM is mostly a GEMV kernel optimized for low batch size while the AWQ kernel is a GEMM kernel optimized for higher batch size.
> 
> Better kernels are being introduced for both GPTQ and AWQ like Marlin and the AWQ Fast-GEMV, which are fast across all batch sizes. If those could be adapted to MoE models, we'll see more improvements.

@chu-tianxiang I understand, thanks for the answer!

2024-03-26 09:16 UTC, omarsou commented
> What is the merge plan here?

+1
We will be more than happy to see this being merged :)

2024-03-27 19:48 UTC, simon-mo commented
Hi everyone, thank you for the active development on this PR. We would really like to include this in the next release. However, we identified few issues: (1) the code made some significant change the existing moe implementation that needs to be carefully reviewed (2) there are some merge conflict (3) the main "code owners" who are familiar with code path for recent moe changes @pcmoritz and @WoosukKwon is lacking in bandwidth. 

Therefore, we would like to push this to the next release v0.4.1 which is targeted around mid April.

2024-03-31 14:41 UTC, robertgshaw2-neuralmagic commented
@chu-tianxiang Thanks for the great PR

This PR effectively supports two cases:

1. There is a fused MoE kernels for the quantization type, in which case we use the fused kernels (matching the logic in current main `Mixtral.py`)
2. There is not a fused MoE kernel for the quantization type, in which case we use the naive looping over the experts with the gemm kernels (matching the logic in current main `MixtralQuant.py`

Supporting both of these cases adds significant complexity to the implementation, since we now have a big if statement around the following:

```python
if not isinstance(self.linear_method, UnquantizedLinearMethod) and not self.linear_method.quant_config.support_fused_moe():
        # case 2 --> there is not a fused kernel
else:
        # case 1 --> there is a fused kernel
```

This impacts each the core methods in the model definitions:
- `__init__` --> now, we need to maintain two scenarios and weight definitions
- `forward` --> now, we need to maintain two possible cases for forward methods
- `load_weights` --> now, we have to have two cases for loading the weights

Since we now have kernels for GPTQ and AWQ, which are by far the most popular methods, I think it makes sense to remove support for case 2 and simply fail if the user tries to run a quantization method that does not support fused_moe execution. 

This will dramatically simplify the code and make it much easier to (a) maintain and (b) add new MoE models in the future.

We are already working on a fused MoE version of Marlin as well. So it will really just be SqueezeLLM that lacks a fused kernel. I think this is a completely worthwhile tradeoff

2024-04-01 13:19 UTC, chu-tianxiang commented
@robertgshaw2-neuralmagic Thanks for the suggestion, the current logic does increase the code complexity of MoE models quite a bit. Inspired by your analysis, I'm thinking that the root cause of complexity is that fused MoE uses tensor parallel while the unfused uses expert parallel, maybe we change the unfused MoE implementation from expert parallel to the very initial tensor parallel. If it works out we can have simple code and full quantization support at the same time.

2024-04-01 18:11 UTC, robertgshaw2-neuralmagic commented
@chu-tianxiang Are you okay if I make a proposal for a refactor?

2024-04-02 03:35 UTC, chu-tianxiang commented
> @chu-tianxiang Are you okay if I make a proposal for a refactor to the logic?

Sure, please feel free to do so.

2024-04-08 14:52 UTC, robertgshaw2-neuralmagic commented
@chu-tianxiang LMK when you're ready for a re-review

The refactor I have been working on basically makes a shared `FusedMoELinear` layer that can be used across `Deepseek`, `Mixtral`, and `QwenMoE`. Should be able to sync up with the changes you have made such far

2024-04-09 05:38 UTC, chu-tianxiang commented
@robertgshaw2-neuralmagic Thanks, it is ready now. Following your suggestion, I removed the expert parallel part and it's much cleaner. Currently tested on Mixtral (fp16, awq, gptq-4bit, gptq-3bit), Deepseek (fp16, gptq-4bit) and Qwen-moe (fp16, gptq-4bit).

2024-04-09 15:22 UTC, robertgshaw2-neuralmagic commented
Sweet - thanks @chu-tianxiang 

Will take a look later this week.

2024-04-18 11:39 UTC, robertgshaw2-neuralmagic commented
Hey @chu-tianxiang - these changes are looking much better, the logic is much simpler and easier to parse

The final architectural change I would want to see to feel comfortable merging is to abstract the fused MoE layer logic from the model definitions into a new class in `linear.py` called `FusedMoELinear`. This would resolve a few problems problems:
- A) We have the same logic for making an MoE layer in `Mixtral` `DeepSeek` and `Qwen`. Having a single implementation will be easier to maintain.

- B) We currently overload `MergedColumnParallelLinear` and `RowParallelLinear` in each model to handle the weight loading. The `FusedMoELinear` class can handle this logic (likely reusing the code from `MergedColumnParallelLinear` and `RowParallelLinear`

- C) We currently have each `Linear` layer creating weights with `create_moe_weights` and each linear constructor requires `expert_id` to be passed. This is confusing. By having `FusedMoELinear`, we can call the `create_moe_weights` just in that class.


### FusedMoELinear Proposal

```python
class FusedMoELinear(torch.nn.Module):
    def __init__(shapes, linear_method):
        # gate_up_proj
        self.ws = linear_method.create_moe_weights(shapes)
        set_weight_attrs(self.ws, {
            "weight_loader": self.weight_loader_merged_column,
        })
       
        # down_proj 
        self.ws = linear_method.create_moe_weights(shapes)
        set_weight_attrs(self.w2s, {
            "weight_loader": self.weight_loader_row_parallel,
        })
       # ...

    # weight loader for gate_up_proj    
    def weight_loader_merged_column(param, loaded_weight, expert_id):
       # refactor to share with MergedColumnParallel?  << make method static in MergedColumnParallel?
       pass

    # weight loader for down_proj
    def weight_loader_row_parallel(param, loaded_weight, expert_id):
       # refactor to share with MergedColumnParallel? << make method static in RowColumnLinear?
        pass

    def forward(hidden_states, router_logic):
        linear_method.apply_moe_weights(**)
```

Then, this layer would be part of Mixtral:

```python
class MixtralMoE(torch.nn.Module):
     def __init__():
          self.gate = ReplicatedLinear()
          # note: this breaks the disk state dict (model.layers.0.mlp.w1 --> model.layers.0.mlp.fused_moe.ws)
          self.fused_moe = FusedMoE()
    def forward(hidden):
          router_logits = gate(hidden)
          return self.fused_moe(hidden, gates)
    
    # handle complexity of state dict remapping here
    def load_weights():
         # model.layers.0.mlp.w1 --> model.layers.0.mlp.fused_moe.ws 
         # model.layers.0.mlp.w2--> model.layers.0.mlp.fused_moe.w2
         # model.layers.0.mlp.w3--> model.layers.0.mlp.fused_moe.w3
```

2024-04-18 11:42 UTC, robertgshaw2-neuralmagic requested changes
See my comments for final requested architectural changes. Also we need tests for this.

It would be nice to have some big model tests and small model tests (that can run on a single GPU).

The small model tests should be possible for deepseek and qwen as they have sizes that fit on a single GPU

2024-04-18 11:44 UTC, robertgshaw2-neuralmagic commented on vllm/model_executor/layers/fused_moe/fused_moe.py
> +def fused_topk(
is the split out of `fused_topk` needed anymore?

2024-05-22 05:23 UTC, jinzhen-lin commented
Hi, is this pr still active? Looking forward to this pr being merged.

2024-05-24 06:36 UTC, chu-tianxiang commented
Sorry I've been quite busy with personal life over the past month, left me with little time to update. Additionally, when I attempted to update last month, I encountered some conflicts that were hard to resolve.

Originally I created the MoE weights by adding an axis to every weights in `linear_weights`, however #3977 removed linear_weights and register as parameters directly. #4342 and #4373 suggested using fully separate logics for linear layer and MoE layer.  Now I don't know how I can create MoE weights without copy-and-paste the `create_weight` method for every quantization method, which is way too inelegant. If anyone can come up a better design, please let me know or feel free to create another PR.

2024-07-05 03:40 UTC, fengyang95 commented
Does this PR support deepseek-v2 awq?

2024-07-05 05:14 UTC, casper-hansen commented
@fengyang95 This was intended for v1 but should be extendable to v2. I hope @robertgshaw2-neuralmagic is able to pick this up at some point to get it through :)

2025-02-17 18:14 UTC, mgoin commented
This has been superseded for a while by Marlin MoE kernels https://github.com/vllm-project/vllm/pull/8217 and https://github.com/vllm-project/vllm/pull/8973

2025-02-17 18:14 UTC, closed without merging