chore(outputs): make return class into dataclass
vllm-project/vllm pull request #3017
Opened 2024-02-24 02:16 UTC by aarnphm

Signed-off-by: Aaron <29749331+aarnphm@users.noreply.github.com>

2024-03-17 11:42 UTC, esmeetu commented
@WoosukKwon As #3452 was merged, i think it should be ok to merge this.

2024-03-17 11:47 UTC, esmeetu requested changes
`__repr__` method in `RequestOutput` class seems redundant when using `dataclass`

2024-03-17 16:57 UTC, youkaichao commented
@aarnphm besides using `dataclass` for class definition, I think you should also change all the usage site of these classes.

2024-10-30 02:41 UTC, aarnphm commented
> @aarnphm besides using `dataclass` for class definition, I think you should also change all the usage site of these classes.

oh sorry I completely forgot about this PR, wdym by "usage site" here?

2025-02-25 19:28 UTC, closed without merging