[Bugfix] Fixed error in slice_lora_b for MergedQKVParallelLinearWithLora
vllm-project/vllm pull request #4609
Opened 2024-05-05 21:16 UTC by FurtherAI

FIX #3524

`MergedQKVParallelLinearWithLora`  `slice_lora_b` throws an error when the passed in `lora_b` contains None.

2024-05-05 21:20 UTC, FurtherAI commented
Ping @Yard1.

2024-05-05 22:17 UTC, simon-mo approved these changes

2024-05-06 01:54 UTC, DarkLight1337 requested changes

2024-05-06 01:54 UTC, DarkLight1337 commented on vllm/lora/layers.py
>      def slice_lora_b(self, lora_b: List[torch.Tensor]) -> List[torch.Tensor]:
You should update the return type to include the possibility of `None` values.

2024-05-06 02:16 UTC, DarkLight1337 commented on vllm/lora/layers.py
>      def slice_lora_b(self, lora_b: List[torch.Tensor]) -> List[torch.Tensor]:
Side note: You should also tag #4605 in this PR so it will be closed upon merge

2024-05-06 04:31 UTC, FurtherAI commented
Good point, it is done. Also updated the fully sharded layers to match.

2024-05-06 04:37 UTC, DarkLight1337 commented
> Good point, it is done. Also updated the fully sharded layers to match.

In case you didn't know, `Optional[torch.Tensor]` is preferred over `Union[torch.Tensor, None]`.

2024-05-07 17:55 UTC, tejeshbhalla commented
can you merge this plz

2024-05-07 17:59 UTC, Yard1 approved these changes
Thanks!

2024-05-07 17:59 UTC, merged