Not all stop sequences are created equal
vllm-project/vllm pull request #534
Opened 2023-07-20 15:20 UTC by zacharyblank

This PR fixes some stop sequences not being matched. When generating and decoding tokens, sometimes a single token with generate the stop sequence **plus additional characters**. This caused `if seq.output_text.endswith(stop_str):` not to behave as expected.

For example. If a stop sequence is defined as `",` and the model generates `","` as a single token, as is the case with `EleutherAI/gpt-neox-20b`, then the stop sequence will not be detected and generation will not stop.

This is a small PR that, instead of checking only the end of the generated sequence, checks the entire sequence for the stop sequence

2023-07-25 21:38 UTC, zhuohan123 requested changes
Thank you for your contribution! Can you fix the formatting error with `format.sh`? In addition, does this change lead to an O(N) string comparison at every iteration, which leads to O(N^2) general complexity? Will this affect the performance of long sequences? Can we somehow just compare `stop_str` with the newly generated token, instead of the whole sequence?

2024-03-13 00:49 UTC, claudiosv commented
I believe #1724  is a dupe of this one. Would like to see this merged though.

2024-03-28 14:10 UTC, hmellor commented
@zacharyblank is this PR still necessary? If yes, do you still plan to get it merged?

2024-03-28 18:17 UTC, njhill commented
https://github.com/vllm-project/vllm/pull/3672 is a more complete fix for this.

2024-03-28 18:50 UTC, closed without merging