[Misc] Various simplifications and typing fixes
vllm-project/vllm pull request #5368
Opened 2024-06-09 22:58 UTC by njhill

Noticed while working on other features, thought it would be cleaner to split into a separate PR.

2024-06-09 23:02 UTC, njhill commented on vllm/worker/model_runner.py
> -
These tensors aren't used in the flashinfer case

2024-06-10 06:46 UTC, DarkLight1337 approved these changes

2024-06-10 06:54 UTC, DarkLight1337 requested changes
Sorry I approved too early. Looks like you broke the speculative decoding code.

2024-06-10 14:42 UTC, njhill commented
Thanks @DarkLight1337! It was a small mistake, have now pushed a fix.

2024-06-11 02:28 UTC, DarkLight1337 approved these changes

2024-06-11 02:29 UTC, merged