[Misc] Update `w4a16` `compressed-tensors` support to include `w8a16`
vllm-project/vllm pull request #5794
Opened 2024-06-24 18:40 UTC by dsikka

# Summary
- Expand support such that we can run `w8a16` models compressed through [`compressed-tensors`](https://github.com/neuralmagic/compressed-tensors)
- This requires changing the supported scheme from `CompressedTensorsW4A16` to `CompressedTensorsWNA16` to support both w4a16 and w8a16/allow use of the same kernels

By Neural Magic

2024-06-24 23:18 UTC, robertgshaw2-neuralmagic commented
LGTM - pending test failure which relied on the old name

2024-06-25 00:54 UTC, dsikka commented
@robertgshaw2-neuralmagic updated

2024-06-25 02:54 UTC, robertgshaw2-neuralmagic commented on tests/quantization/test_compressed_tensors.py
> +        assert isinstance(qkv_proj.scheme, CompressedTensorsWNA16)
Can you add a test case for w8a16?

2024-06-25 02:54 UTC, robertgshaw2-neuralmagic requested changes
Please add a test case. Otherwise LGTM

2024-06-25 17:33 UTC, robertgshaw2-neuralmagic approved these changes
lgtm

2024-06-25 19:23 UTC, merged