Fix mqa is false case in gpt_bigcode
vllm-project/vllm pull request #806
Opened 2023-08-20 15:29 UTC by zhaoyang-star

cc @zhuohan123

2023-08-21 22:53 UTC, zhuohan123 requested changes
Thanks for the fix! Left some small comments on style.

2023-08-21 22:53 UTC, zhuohan123 commented on vllm/model_executor/models/gpt_bigcode.py
> +            total_num_heads // self.tensor_model_parallel_world_size
Nit: Please use parenthesis for line continuation according to google python style guide.
```suggestion
        self.num_heads = (
            total_num_heads // self.tensor_model_parallel_world_size)
```

2023-08-21 22:53 UTC, zhuohan123 commented on vllm/model_executor/models/gpt_bigcode.py
> +                    total_num_heads // self.tensor_model_parallel_world_size
Ditto on line continuation

2023-08-22 00:33 UTC, zhaoyang-star commented
> Thanks for the fix! Left some small comments on style.

Fixed. Please have a review again. @zhuohan123 
PR about QKV gemm fuse in gpt_bigcode will be committed later.

2023-08-22 05:12 UTC, zhuohan123 approved these changes
LGTM! Thank you for your contribution!

2023-08-22 05:22 UTC, merged