[MISC] Replace input/output token throughput with token throughput
vllm-project/vllm pull request #8164
Opened 2024-09-04 18:41 UTC by comaniac

I found that the input and output token throughput in the benchmark serving script is misleading, because they are calculated by the end to end latency instead of prefill or decode latency. While it's not clear how we could measure prefill or decode latency separately, this PR replaced these metrics directly with token throughput.

@KuntaiDu please help review and let me know whether this would affect the performance benchmark.

Also cc @ywang96 @SolitaryThinker

2024-09-04 18:52 UTC, ywang96 approved these changes
LGTM! Per our offline discussion, TTFT and ITL are better metrics to reflect prefill and decode performance in an online setting, so this change makes sense to me.

2024-09-04 18:57 UTC, simon-mo commented
cc @mgoin where we originally added this. I think the main reason behind it was for needing to know the output throughput...

2024-09-04 19:00 UTC, ywang96 commented
> cc @mgoin where we originally added this. I think the main reason behind it was for needing to know the output throughput...

I see, I guess in that case maybe we should just get rid of input throughput? The problem with this metric is that in almost all cases it’s underestimating the actual throughput capacity of prefill.

2024-09-04 19:11 UTC, mgoin requested changes
I would very much prefer to keep output throughput separate, since that is the usual "token throughput" reported by many other projects, including mlperf and trt-llm https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance/perf-overview.md#throughput-measurements

I agree the input throughput metric as-is is not accurate, so we can remove it for now, but we should try to produce it in the future as it is useful for understanding system performance.

2024-09-04 19:27 UTC, comaniac commented
Well my point is this measurement of both input and output throughput are inaccuracy and misleading especially with chunked prefill enabled. I personally feel comparing this inaccurate metric cannot reflect to real performance bottlenecks and may give people a wrong impression so we should not rely it. Meanwhile, I could understand the concern that this inaccurate metric is being used everywhere at this moment and people want to know this value when benchmarking vLLM, so I won't fight back if you champion on keeping output token throughput.

I'll update the PR to:
1. Keep output throughput.
2. Replace input throughput with total token throughput.

2024-09-04 19:37 UTC, mgoin commented on benchmarks/benchmark_serving.py
> +                                    metrics.total_token_throughput))
```suggestion
    print("{:<40} {:<10.2f}".format("Output token throughput (tok/s):",
                                    metrics.output_throughput))
    print("{:<40} {:<10.2f}".format("Total Token throughput (tok/s):",
                                    metrics.total_token_throughput))
```

2024-09-04 19:37 UTC, mgoin approved these changes
Okay that is a reasonable state for me, thank you!

2024-09-04 19:47 UTC, comaniac commented on benchmarks/benchmark_serving.py
> +                                    metrics.total_token_throughput))
Oops good catch.

2024-09-04 20:23 UTC, merged

2024-09-05 10:19 UTC, Andy0422 commented
> I would very much prefer to keep output throughput separate, since that is the usual "token throughput" reported by many other projects, including mlperf and TRT-LLM https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance/perf-overview.md#throughput-measurements
> 
> I can understand if the thought is that input throughput as-is is not accurate, so we can remove it for now, but we should try to produce it in the future as it is useful for understanding system performance. However I think it is accurate to report output throughput over the total time.
> 
> Reference from TRT-LLM benchmarking code that their token throughput is output tokens only https://github.com/NVIDIA/TensorRT-LLM/blob/78f5c2936b7bdaa56859075a3f2fcc5a63952134/benchmarks/cpp/gptManagerBenchmark.cpp#L607
> 
> ```c++
>         mTokenThroughput = totalOutputTokens / (mTotalLatency / 1000);
> ```

Hi, I just confused why vllm requests input length and output length to compute the total_num_tokens in throughput calculations? 
e.g. in benchmark_throughput 
    total_num_tokens = sum(prompt_len + output_len
                           for _, prompt_len, output_len in requests)

It seems has different definitions on throughput.