[WIP][Sampler] Vectorized sampler
vllm-project/vllm pull request #820
Opened 2023-08-22 00:28 UTC by Yard1

WIP and pretty messy right now.

Using the modified throughput benchmark with `python benchmarks/benchmark_throughput.py --backend vllm --dataset "./ShareGPT_V3_unfiltered_cleaned_split.json" --model meta-llama/Llama-2-13b-chat-hf --tokenizer meta-llama/Llama-2-13b-chat-hf --num-prompts=1000` and one A100-80, I get the following results:

```
baseline: Throughput: 3.70 requests/s, 1771.58 tokens/s
this PR: Throughput: 4.77 requests/s, 2280.04 tokens/s
```

which would be a 1.28x improvement.

Didn't do any proper correctness testing yet.

2023-08-23 01:51 UTC, Yard1 commented
Updated benchmark to also apply top_p.

```
baseline: Throughput: 3.58 requests/s, 1710.60 tokens/s
PR: Throughput: 4.69 requests/s, 2243.01 tokens/s
```
1.31x improvement

2023-08-23 01:54 UTC, Yard1 commented
I have also compared outputs of the benchmark on the ShareGPT dataset, and they are identical between master and this PR (meaning that there is no impact on correctness).

2023-08-23 02:12 UTC, Yard1 commented on vllm/model_executor/layers/sampler.py
> +    occurences = _batched_bincount(input_ids, 1, logits.shape[1])
```suggestion
    occurences = _batched_bincount(input_ids, 1, logits.shape[1])

    # We follow the definition in OpenAI API.
    # Refer to https://platform.openai.com/docs/api-reference/parameter-details
```

2023-08-23 15:53 UTC, hongqing1986 commented on vllm/model_executor/layers/sampler.py
> +        if len(sampling_type_offsets) > 1:
shoud be:
if len(sampling_type_offsets) > 0:

2023-08-23 16:25 UTC, Yard1 commented on vllm/model_executor/layers/sampler.py
> +        if len(sampling_type_offsets) > 1:
```suggestion
        if len(sampling_type_offsets) > 0:
```

2023-08-23 17:50 UTC, Yard1 commented
Using modified benchmark and llama-2-7b on A100-80:
```
baseline: Throughput: 4.67 requests/s, 2233.30 tokens/s
PR: Throughput: 6.84 requests/s, 3272.51 tokens/s
```
x1.47 improvement

As expected, the improvement is bigger the smaller the model (and thus more time is spent in sampling).

2023-08-23 22:49 UTC, scv119 commented
benchmark llama70-b with A100-40 * 4, 512 context length and 128 generation, 500 requests
```
baseline: dur_s 133.22 tokens_per_s 1807.24 qps 3.75 successful_responses 500
PR: dur_s 114.26 tokens_per_s 2108.07 qps 4.38 successful_responses 500 
```

2023-08-25 04:02 UTC, Yard1 commented on vllm/model_executor/layers/sampler.py
> +                          replacement=False,
```suggestion
                          replacement=True,
```

2023-09-05 17:46 UTC, WoosukKwon reviewed
@Yard1, thanks for submitting the PR. Before I go deeper into the PR, could you please update the branch with the latest commit?

2023-09-05 17:46 UTC, WoosukKwon commented on vllm/model_executor/layers/sampler.py
> +        if sampling_type_indices.max() > 0:
```suggestion
        if sampling_type_indices.max() > SamplingType.GREEDY:
```

2023-09-05 18:29 UTC, Yard1 commented on benchmarks/benchmark_throughput.py
> +            f.write(output.__repr__() + "\n")
Yeah, I will revert the changes to the benchmarking script later.

2023-09-05 18:30 UTC, Yard1 commented on benchmarks/benchmark_throughput.py
> +    do_sample = False
Allows us to alternate between greedy and stochastic sampling for requests

2023-09-05 18:47 UTC, Yard1 commented
@WoosukKwon updated, ptal

2023-09-06 18:55 UTC, scv119 commented on vllm/model_executor/layers/sampler.py
> +                                               minlength=3).cumsum(0)[:-1]
minlength=len(SamplingType)

2023-09-06 18:55 UTC, scv119 commented on vllm/model_executor/layers/sampler.py
> +            temperatures = _get_temperatures(input_metadata)
should we apply the index here as well?

2023-09-06 18:55 UTC, scv119 commented on vllm/model_executor/layers/sampler.py
> +            top_ps, top_ks = _get_top_p_top_k(input_metadata, self.vocab_size)
ditto

2023-09-06 19:00 UTC, scv119 commented on vllm/model_executor/layers/sampler.py
> +            non_greedy_offset = sampling_type_offsets[0]
nit: consider 
`sampling_type_offsets[SamplingType.GREEDY]`
and other places too.

2023-09-06 19:02 UTC, scv119 reviewed
also consider add a test?

2023-09-08 02:07 UTC, scv119 commented
lgtm

2023-09-12 06:24 UTC, WoosukKwon commented
@Yard1 I got an error when running `examples/llm_engine_example.py`:

```
File "/home/workspace/vllm/vllm/model_executor/layers/sampler.py", line 98, in forward
    assert len(temperatures) == non_greedy_logits.shape[0]
AssertionError
```

2023-09-12 07:14 UTC, Yard1 commented
@WoosukKwon Good catch! Just pushed a fix.

2023-09-12 07:20 UTC, Yard1 commented on vllm/worker/worker.py
> +                                         len(seq_ids))
```suggestion
            sampling_type_indices.append(sampling_params.sampling_type)
```

2023-09-12 07:30 UTC, WoosukKwon requested changes
@Yard1 Thanks for the PR. It seems the performance improvement is quite significant! However, I'm a bit worried that this PR 1) includes unnecessary changes, and 2) complicates the sampler logic.

For 1), could you revert back the unnecessary changes? I pointed out a few places in the code.
For 2), do you have any idea to simplify the code? I think the complexity mainly comes from a lot of tensor/list indexing operations, and sort-gathers. Can you somehow reduce the use of them?

2023-09-12 16:54 UTC, Yard1 commented on vllm/model_executor/layers/sampler.py
> +                _apply_top_p_top_k_in_place(non_greedy_logits, p, k)
right now it's necessary for the p's and k's to be indexed correctly

2023-09-12 16:54 UTC, Yard1 commented on vllm/model_executor/layers/sampler.py
> +                for p, k in zip(top_ps, top_ks))
One loop instead of 2

2023-09-12 16:55 UTC, Yard1 commented on vllm/worker/worker.py
> +
I believe so, but I can revert it

2023-09-12 16:57 UTC, Yard1 commented
@WoosukKwon Thanks for the feedback, let me see if I can reduce unnecessary changes.

As for the compelxity, the current code is optimized for memory and speed. I am not sure if it's possible to reduce the complexity without impacting performance. I am happy to add more comments and change the code structure for more readability.

2023-09-22 06:18 UTC, Yard1 commented
Closed in favor of https://github.com/vllm-project/vllm/pull/1048

2023-09-22 06:18 UTC, closed without merging