[CI/Build]: Add Bandit security check to workflow
vllm-project/vllm pull request #8353
Opened 2024-09-11 04:57 UTC by ChengyuZhu6

- Integrate Bandit to scan for security issues in the codebase.
- Configure Bandit to fail the workflow if any high-severity issues are found.

e.g.:

```bash
$ bandit -r . --severity-level high
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.10.12
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:12
Run started:2024-09-11 04:37:49.395569

Test results:
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.9/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: ./collect_env.py:95:8
94                               stderr=subprocess.PIPE,
95                               shell=shell)
96          raw_output, raw_err = p.communicate()
97          rc = p.returncode
98          if get_platform() == 'win32':
99              enc = 'oem'

--------------------------------------------------

Code scanned:
        Total lines of code: 135058
        Total lines skipped (#nosec): 0

Run metrics:
        Total issues (by severity):
                Undefined: 0
                Low: 3887
                Medium: 33
                High: 1
        Total issues (by confidence):
                Undefined: 0
                Low: 20
                Medium: 28
                High: 3873
Files skipped (0):
```

2024-09-13 03:56 UTC, ChengyuZhu6 commented
rebase to main only to see if the failures in CI can be fixed.

2024-09-19 09:32 UTC, ChengyuZhu6 commented
kindly ping @simon-mo

2025-02-25 04:05 UTC, simon-mo commented
cc @russellb if you think this will be useful.

2025-02-28 16:03 UTC, russellb requested changes
I'm OK with this in general.  Some comments:

* I'd like it to run cleanly before merging. I see you fixed the warning from `collect_env.py`. When I ran it, I see several others (all about using md5).
* It would be nice to integrate this into our `pre-commit` configuration to make it easier to run locally the same way we'd run it in CI. That would also include changing the CI job to use pre-commit to run it.
* We need to configure this to skip everything ignored by `.gitignore`. For example, I have a python virtualenv in my vllm directory, so it scanned everything in there and took forever.

cc @simon-mo

2025-04-26 15:49 UTC, russellb commented
Given the time since last update on this PR, I'm going to close it out. Please feel free to reopen if you're interested in updating it!

2025-04-26 15:49 UTC, closed without merging