[Frontend] MQLLMEngine supports profiling.
vllm-project/vllm pull request #8761
Opened 2024-09-24 05:05 UTC by abatom

MQLLMEngine supports profiling.

1. The profiling-related protocols and APIs from previous versions have been adapted to MQLLMEngine.

2024-09-24 19:25 UTC, njhill reviewed
Thanks @abatom, looks great! Could you run `./format.sh` to sure the formatting is correct.

2024-09-24 19:25 UTC, njhill commented on vllm/engine/multiprocessing/client.py
> +            socket = self.input_socket)
nit: formatting
```suggestion
            socket=self.input_socket)
```

2024-09-24 19:25 UTC, njhill commented on vllm/engine/multiprocessing/client.py
> +            socket = self.input_socket)
```suggestion
            socket=self.input_socket)
```

2024-09-25 05:20 UTC, abatom commented
# ./format.sh 
vLLM yapf: Done
vLLM mypy:
Success: no issues found in 122 source files
Success: no issues found in 294 source files
Success: no issues found in 15 source files
Success: no issues found in 12 source files
Success: no issues found in 17 source files
Success: no issues found in 17 source files
Success: no issues found in 17 source files
Success: no issues found in 87 source files
Success: no issues found in 6 source files
Success: no issues found in 15 source files
Success: no issues found in 22 source files
vLLM mypy: Done
vLLM codespell: Done
All checks passed!
vLLM ruff: Done
vLLM isort: Done

2024-09-25 09:14 UTC, njhill requested changes
@abatom it won’t be the async version of the executor here

2024-09-25 09:14 UTC, njhill commented on vllm/engine/multiprocessing/engine.py
> +        if type(self.engine.model_executor) is GPUExecutorAsync:
```suggestion
        if type(self.engine.model_executor) is GPUExecutor:
```

2024-09-25 09:14 UTC, njhill commented on vllm/engine/multiprocessing/engine.py
> +        if type(self.engine.model_executor) is GPUExecutorAsync:
```suggestion
        if type(self.engine.model_executor) is GPUExecutor:
```

2024-09-25 13:59 UTC, abatom commented
@njhill What do I need to do next?

2024-09-25 15:40 UTC, njhill approved these changes
Thanks @abatom

2024-09-25 16:08 UTC, abatom commented
@njhill, what should I do for "Required statuses must pass before merging" ?

2024-09-25 16:14 UTC, njhill commented
@abatom these are unrelated CI test failures, we can override to merge this.

2024-09-25 16:37 UTC, merged